### ISSUE TITLE
FR: Text-Formating like Markdown

### ISSUE THREAD

**Issue by demlak** [nextcloud/forms#1177] opened 2022-04-17 20:54 UTC
**Is your feature request related to a problem? Please describe.**
We want to have some Informations to be more focused.

**Describe the solution you'd like**
We would like to have Markdown in Description field to format Text with Bold, Underline, etc..

**Describe alternatives you've considered**
Alternative: Accept HTML

thx

**Comment by Chartman123** [comment] 2022-04-18 09:53
Duplicate of #489

**Closed by Chartman123** 2022-04-18 09:53 UTC
Labels: enhancement, 0. Needs triage
