### ISSUE TITLE
Directly write form responses to document within cloud

### ISSUE THREAD

**Issue by jotoeri** [nextcloud/forms#263] opened 2020-03-31 08:27 UTC
[As mentioned by @forteller](https://github.com/nextcloud/forms/issues/34#issuecomment-606182611)

> And if the results could automatically be added to a editable document as the come in, instead of having to first export it, that would be really great. That's one of the huge advantages of Google Forms.

**Comment by jancborchardt** [comment] 2020-05-01 00:12
This is a duplicate of https://github.com/nextcloud/forms/issues/5, let’s continue there :)

**Closed by jancborchardt** 2020-05-01 00:12 UTC
Labels: 1. to develop, enhancement, integration
