### ISSUE TITLE
Allow links to be embedded into description

### ISSUE THREAD

**Issue by blackfisch** [nextcloud/forms#1253] opened 2022-07-15 10:35 UTC
**Nextcloud:**
- Nextcloud-Version: 24.0.2
- Forms-Version: 2.5.1

**Is your feature request related to a problem? Please describe.**
When creating forms, the possibility to embed links can be helpful to clear up things, include example images and more. Forms currently does not allow embedding of links.

**Describe the solution you'd like**
Automatically wrap URLs in description within a `<a href='...'></a>` tag to make them clickable.

**Describe alternatives you've considered**
Placing links inside description does display them, however them not being interactable reduces user experience a lot and might cause issues for some people.

**Comment by Chartman123** [comment] 2022-08-22 09:41
@jotoeri Isn't this a duplicate of #489 as it can be realised with Markdown?

**Comment by jotoeri** [comment] 2022-08-22 20:58
Uhm, more or less - Links can be realised with markdown, yes. But regarding a possible timline i could imagine, that we e.g. implement some link & bold formatting feature before implementing a full markdown support. So probably i'd keep this one separate for now.

**Closed** 2023-01-31 11:54 UTC
Labels: enhancement, 1. to develop
