### ISSUE TITLE
Write to table xls

### ISSUE THREAD

**Issue by rougerouter** [nextcloud/forms#1451] opened 2023-01-13 21:13 UTC
**Nextcloud (please complete the following information):**
- Nextcloud-Version: [e.g. 19.0.0]
- Forms-Version: [e.g. 2.0.0-beta4]

**Is your feature request related to a problem? Please describe.**
**A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

It's not a problem, but your form should write to a table, similar to Google Forms. So much more convenient for analysis and it's on going, so you don't have to export to csv..............draggggg!**
I don't use your app, just because it does not have this functionality. I am really nobody, so you whether you care to make this change is totally up to you.
It would be greatly appreciated and I think everyone would love it!

**Describe the solution you'd like**

Each field should populate a record in a table. Should be an easier way to make it work. Works for Google!
Thanks! 

**Describe alternatives you've considered**

**Additional context**

**Comment by jotoeri** [comment] 2023-01-13 21:37
Duplicate of #5 
Please search for existing issues before opening a new one.

**Closed by jotoeri** 2023-01-13 21:37 UTC
Labels: enhancement, 0. Needs triage
