### ISSUE TITLE
Separator character

### ISSUE THREAD

**Issue by eaCodet** [nextcloud/forms#1092] opened 2021-12-22 09:05 UTC
**Nextcloud (please complete the following information):**
- Nextcloud-Version: [e.g. 19.0.0]
- Forms-Version: [e.g. 2.0.0-beta4]

**Is your feature request related to a problem? Please describe.**
If there is in a text answer a carriage return character this character is interpreted as end of data set. 

**Describe the solution you'd like**
I would like to choose the separating character for each form I create (e.g. # as separating character)

**Describe alternatives you've considered**
manual work at the downloaded csv-file :-( or asking for not using carriage return in text answers :-(

**Comment by jotoeri** [comment] 2021-12-22 10:01
Duplicate of #683
Please see https://github.com/nextcloud/forms/issues/683#issuecomment-727578019

**Closed by jotoeri** 2021-12-22 10:01 UTC
Labels: enhancement, 0. Needs triage
