### ISSUE TITLE
Zooming in breaks the layout

### ISSUE THREAD

**Issue by PVince81** [nextcloud/forms#1258] opened 2022-07-15 15:56 UTC
Some parts overlap and some parts of the interface are cut off by other ones at 200 precent zoom.

![image](https://user-images.githubusercontent.com/277525/179261128-bd4631e2-4caa-47bb-9402-1e28b1e47b2a.png)

**Comment by susnux** [comment] 2022-10-26 10:24
I can not reproduce this with 3.0.1, so I think this is fixed?
See this recording (zooming to 400% and then using it at 200% zoom):

https://user-images.githubusercontent.com/1855448/198002790-021eac5a-5459-4539-a63e-178b579b923a.mp4

**Comment by Chartman123** [comment] 2022-10-26 10:39
@susnux haven't tried it myself by now. Did you also check the layout when the sidebar is opened?

**Comment by susnux** [comment] 2022-10-26 10:44
Looks like this @ 200% zoom:

https://user-images.githubusercontent.com/1855448/198006390-b6384596-5072-42d4-9192-71d7b0aced2a.mp4

Only the question options are overlapped by the sidebar, but this is also the case for 100% zoom.

**Comment by Chartman123** [comment] 2022-10-26 10:56
OK, thanks :) So I'd say that the cause for the design problems has been fixed in the vue components already :)

@PVince81 can you please confirm if this has also been fixed for you?

**Comment by susnux** [comment] 2023-02-22 10:25
I would say this is fixed upstream by `@nextcloud/vue`. Please reopen if this is still reproducible for you.

**Closed by susnux** 2023-02-22 10:25 UTC
Labels: bug, 1. to develop, design
