### ISSUE TITLE
Uploading a CSV file to quicly create a form

### ISSUE THREAD

**Issue by Tizi44** [nextcloud/forms#102] opened 2019-10-18 08:37 UTC
**Which Forms version are you running?**
1.0.3

**Nextcloud or ownCloud?:**
Nextcloud

**Nextcloud/ownCloud version:**
16.0.5

**Actual behaviour**

Option not available yet
**Expected behaviour**

Uploading a CSV file to create the form

**Comment by skjnldsv** [comment] 2020-04-29 16:50
@jancborchardt does it make sense to have?
Wouldn't it be better as json? I guess we could support csv/json.
Does google form supports exporting/importing as thos files?

**Comment by jancborchardt** [comment] 2020-04-30 07:13
> Does google form supports exporting/importing as thos files?

This is the core question: Where would this data come from?

@Tizi44 can you elaborate? Because we need some format or standard we could adhere to, and a Google Forms (or Typeform) export we could and should indeed support.

**Comment by Tizi44** [comment] 2020-04-30 09:14
Hey @jancborchardt , 
The idea behind that was to easily share forms and even editing them without the application form. 
It would better with json format Indeed.

**Comment by skjnldsv** [comment] 2020-04-30 09:36
@Tizi44 but it only make sense if this file can be used in other software?
Having a json file is super technical and will not make any sense to 99.99% of users :)

**Comment by Tizi44** [comment] 2020-04-30 12:23
@skjnldsv I thought as well that it would need a little of skills for non tech person to edit json file.
But it might be at least a step through flexiblility and portability. 
I looked for a while for an app form that can offer that possibility, and I found none. 
This little plus could stand out nextcloud form above others form app  like google or Limesurvey I think.

**Comment by jancborchardt** [comment] 2020-04-30 23:50
The issue is that every functionality needs to be first developed and then also maintained to ensure it stays working.

Because there is no common standard for this and we are unaware of any other system which has this functionality, this is not something we are likely to do. Hence I’ll close this issue for now, hope you understand. :)

**Closed by jancborchardt** 2020-04-30 23:50 UTC
Labels: 0. Needs triage, enhancement, integration, needs info
