### ISSUE TITLE
Able to embed the form as 3rd party

### ISSUE THREAD

**Issue by JOduMonT** [nextcloud/forms#698] opened 2020-11-25 15:45 UTC
It would be wonderful if it was possible to embed these form as 3rd parties into a website

**Comment by jotoeri** [comment] 2020-11-25 18:54
Duplicate of #324 
Please search next time for existing issues and use the given issue-template when opening a new one.

**Closed by jotoeri** 2020-11-25 18:54 UTC
Labels: 0. Needs triage, enhancement

**Comment by JOduMonT** [comment] 2020-11-29 02:30
> Please search next time

sorry I did, but probably too fast :)
