### ISSUE TITLE
Can we share forms in edit mode, please?

### ISSUE THREAD

**Issue by nikkilocke** [nextcloud/forms#2216] opened 2024-06-19 17:30 UTC
**Nextcloud (please complete the following information):**

-   Nextcloud-Version: 28.0.6
-   Forms-Version: 4.2.4

**Is your feature request related to a problem? Please describe.**
We organise in teams, each of which is a Nextcloud Group. We would like a whole team to be able to edit a Form. Currently forms can only be owned by one individual. You can attempt to transfer the ownership of a form, and the list you can transfer to includes groups - but attempting to transfer to a group gives an error.

**Describe the solution you'd like**
Either
1. Allow transferring the ownership of a form to a Nextcloud Group, so all members of the group can edit the form definition (sounds hard to me)
or
2. Allow sharing a form with other users (and/or groups?) in edit mode, so that they, too, can edit the form definition.

I realise there could be issues if two people attempt to edit the form definition at the same time, and I do not expect the app to cope with that (happy for the most recent save to take precedence, or a locking system, or whatever is easiest for you).

**Comment by nikkilocke** [comment] 2024-06-19 17:30
P.S. I have access to a PHP programmer who could spend some time on this, with suitable guidance.

**Comment by Chartman123** [comment] 2024-06-19 18:06
Duplicate of #322

**Closed** 2024-06-19 18:06 UTC
Labels: enhancement, 0. Needs triage
