### ISSUE TITLE
Nextcloud Forms not installable on Nextcloud Hub 9 (Version 30.0.0) due to unmet dependencies

### ISSUE THREAD

**Issue by FRIEDRDAN** [nextcloud/forms#2341] opened 2024-10-01 14:10 UTC
Description:
After upgrading to Nextcloud Hub 9 (Version 30.0.0), it is no longer possible to install the Nextcloud Forms app. The following error is shown when attempting installation:
“This app cannot be installed because the following dependencies are not fulfilled: Server version 29 or lower is required.”

This indicates that the Forms app has a version restriction that prevents it from being installed on Nextcloud Hub 9, even though the app was functioning properly on earlier Nextcloud versions.

Steps to reproduce:

Upgrade Nextcloud to Hub 9 (Version 30.0.0).
Try to install/enable the Nextcloud Forms app.
The installation fails due to unmet dependencies.
Expected behavior:
Nextcloud Forms should install and work properly on Nextcloud Hub 9.

Actual behavior:
The app cannot be installed, with the error message indicating that it requires a server version 29 or lower.

Error Message: “This app cannot be installed because the following dependencies are not fulfilled: Server version 29 or lower is required.”

Environment:

Nextcloud Version: 30.0.0 (Nextcloud Hub 9)
Nextcloud Forms Version: Version 4.2.4, AGPL-lizensiert

Additional context:
The Forms app was last updated 4 months ago, and it seems that the app’s compatibility has not been extended to support Nextcloud Hub 9. Could you please update the app to support the latest Nextcloud version? This would greatly help users relying on the Forms functionality.

Thank you for addressing this issue!

**Comment by Chartman123** [comment] 2024-10-01 14:12
Duplicate of #2334

**Closed by Chartman123** 2024-10-01 14:12 UTC
Labels: duplicate
