### ISSUE TITLE
conditional sub forms 

### ISSUE THREAD

**Issue by daMark-de** [nextcloud/forms#1716] opened 2023-09-16 18:37 UTC
**Is your feature request related to a problem? Please describe.**
Let's take a survey about "mobility" as an example.
There can be a question "Did you ever use a ....?" and the options "train", "car", "bike"
In the next step(s) we want to ask questions about using a "train", "car" and "bike" - but only if the option is marked.

**Describe the solution you'd like**
There are question types which have options. The others are not relevant in this case.
Each option can have another input field. Let's call it "subform". If you enter a name there you are expected to define a subform with this name later. It can be initialized and shown immediately below the question which define the subfrom name. If you leave the subform-field empty the option is not connected to a subform
(Or you have to add a "question" of type "subform" and name it to be able to select this name in a selection field for options in questions" instead of defining the name by entering it into an input field with an option.)
The same name for the subform can be used for more than one option and even with more than one question.
The subform must follow the options which use it's name.
Subfroms can be nested.
Editing a subform is like editing the main form. (In a sub window or in a "list"-view which can be fold und infold?)
If you fill the form the subform is invisible or marked inactive with none of the questions shown. You see it and can enter it if it is activated by selecting one of the appropriate options.
An export of a form with subforms is not one csv-file but a zip file which includes one csv-file for the main form and one for every subform. This would result in smaller csv-files but there is still the possibility to have only one csv-file covering the main form and all subforms.

So far my first ideas.

**Comment by Chartman123** [comment] 2023-09-16 19:53
Duplicate of #358

**Closed by Chartman123** 2023-09-16 19:53 UTC
Labels: enhancement, 0. Needs triage

**Comment by Chartman123** [comment] 2023-09-16 19:55
Please go to the original issue and post your thougts there, if they are not already mentioned there :)
