### ISSUE TITLE
Feature request: Editing form after creation 

### ISSUE THREAD

**Issue by phonon112358** [nextcloud/forms#201] opened 2020-02-19 15:52 UTC
**Which Forms version are you running?** (see apps page) 1.1.0

**Nextcloud or ownCloud?:** NC

**Nextcloud/ownCloud version:** (see Nextcloud admin page) 18.0.1

### Steps to reproduce
1. Create a new form with some questions
2. Save it

### Actual behaviour
There seems to be no way to edit the questions or correct typos.

### Expected behaviour
Some button for editing should be shown to the creator/admin

**Comment by neilcwhite** [comment] 2020-02-24 09:54
I'll second that, for me the possibilities of using forms is massive, however without the functionality of editing the forms created it becomes a none starter for me.

**Comment by vincems** [comment] 2020-03-04 02:56
Definitely a seriously important feature.
I cannot find any evidence of edit feature either.

**Comment by schniepp** [comment] 2020-03-09 16:34
Of course, one has to be a bit more careful here: what if the forms get changed after some users have already responded? Perhaps best if editing was disabled after at least 1 user has already responded.

Alternatively, it could simply spit out a warning. A more sophisticated approach would be to not allow the addition or removal of questions. That way, typos could still be fixed after launching the poll. But still, it has the possibility that the response analysis becomes tricky if not all respondents saw the same form.

**Comment by schniepp** [comment] 2020-03-09 16:37
I actually like the independently proposed idea of duplicating a form (#202). This way, one would not mess with a poll already started. Instead, all the edits would apply to a new form.

**Comment by phonon112358** [comment] 2020-03-09 17:08
yes, I see the problem... 
I think that a displaying a (big) warning if at least one person has already answered would be the best... Then, the creator can still decide by herself whether he really wants to change the form (for example, if the person who has already answered, saw a typo or some error and told it to the creator)...

I don't like the idea to solve this via duplication since this might end in a huge mess of duplicated forms with only very little differences. For example, if one created a form and noticed a typo right after the creation, then some hours later, one think again about the form and change one question slightly, then someone who has answered the form notices a further typo and so on, there would be a lot of forms and the analysis would be even more difficult than one single changed form... 
But that is only my opinion.

**Comment by pwepwe973** [comment] 2020-03-09 17:44
up up up

**Comment by forteller** [comment] 2020-03-30 16:19
All other form tools I've seen has the option to edit. This is an important feature! If you need to clearify something after spreading the link it's not an option to do that in a copy and then having to spread the new link. Sure, it's good to have a clone option too, but not instead.

**Comment by mcgodwin** [comment] 2020-04-28 17:33
Crucial feature indeed! I would like to use this app to run my UX questionnaires (and avoid Google & co), but if I have to re-create the form every time I need to change a word, it's going to be a huge bummer ಠ_ಠ

**Comment by skjnldsv** [comment] 2020-04-29 16:37
Duplicate of #1

**Closed by skjnldsv** 2020-04-29 16:37 UTC
