### ISSUE TITLE
Share edit per Missions with other Group / User

### ISSUE THREAD

**Issue by Juju-bln** [nextcloud/forms#1096] opened 2022-01-06 08:34 UTC
Hey,

i really like your app for NextCloud, but i have one (for me) important problem:
Is it possible, that you can add a function to share the edit permission with other groups / users?

I hope you undestand my requestion, my english is not the best. 

Greetings

**Comment by jotoeri** [comment] 2022-01-11 21:21
Duplicate of #322 
Please search for existing issues before opening a new one. 😉

**Closed by jotoeri** 2022-01-11 21:21 UTC
