### ISSUE TITLE
Sharing result of a survey

### ISSUE THREAD

**Issue by teach0r** [nextcloud/forms#1077] opened 2021-11-15 15:07 UTC
Hello dear Forms team,

Your app is really great!
Is it possible to incorporate the feature that the result of a Nextcloud survey is shared with other Nextcloud users.

That would be a great addition.

Regards
Matt

**Comment by jotoeri** [comment] 2021-11-15 19:38
Duplicate of #455 
Please search for existing issues before opening a new one. 😉

**Closed by jotoeri** 2021-11-15 19:38 UTC
Labels: enhancement, 0. Needs triage
