### ISSUE TITLE
t schoukld be important to save responses as xls in NC files. AND added a new row in xl sheet when a new responce is recieved.

### ISSUE THREAD

**Issue by digitalrevisor** [nextcloud/forms#668] opened 2020-11-08 19:25 UTC
**Nextcloud (please complete the following information):**
- Nextcloud-Version: [e.g. 19.0.0]
- Forms-Version: [e.g. 2.0.0-beta4]

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jotoeri** [comment] 2020-11-08 20:21
Please fill the given Template, to give us information! Further, please search for existing issues before creating a new one.
From title, i classify it as duplicate of #5

**Closed by jotoeri** 2020-11-08 20:21 UTC
Labels: 0. Needs triage, enhancement
