### ISSUE TITLE
Linked spreadsheet: allow customisation of the results file

### ISSUE THREAD

**Issue by acress1** [nextcloud/forms#2279] opened 2024-08-11 19:40 UTC
Hi everyone,

**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
Cannot customise the results file (hide columns, set the background colour of some cells, justify the text, etc.), because at each new answer, it goes back to the initial setup (with timestamp, user, etc.)

**To Reproduce**

1. Create a form
2. Answer to the form
3. In the form settings, enable the results file (.ods in my case)
4. In the ods file, customise the cells, hide some columns (timestamp and user for me)
5. Go back to the form, create a new answer
6. Go back to the results file and you can see that everything disappeared

**Expected behavior**
I’d like the cells to behave as I decided to (hidden columns to stay hidden, background colour to stay blue …)

Thanks !
Cress

**Comment by susnux** [comment] 2024-08-14 12:32
Duplicate of https://github.com/nextcloud/forms/issues/1970

**Closed by susnux** 2024-08-14 12:32 UTC
Labels: enhancement, 1. to develop
