### ISSUE TITLE
Redirect To Login Page for internal users forms

### ISSUE THREAD

**Issue by ridhwn** [nextcloud/forms#706] opened 2020-12-10 14:49 UTC
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 19.0.0
- Forms-Version: 2.0.4

**Is your feature request related to a problem? Please describe.**
If i set the forms to show to all users of this instance or choose user to share with and share the that link to the internal users. The users when they click the link will appear form doesn't exist. I understand user need to login to see the form, but can't it redirect users to login page if the form where private rather then showing the form doesn't exist? or any button to go to login page or a message showing this form is private please login to response?

**Comment by jotoeri** [comment] 2020-12-10 16:51
Duplicate of #539. Scheduled there for V2.1. Please search for existing issues next time.

- If necessary, you can find a manual quick-fix there too.

**Closed by jotoeri** 2020-12-10 16:51 UTC
Labels: 0. Needs triage, enhancement

**Comment by ridhwn** [comment] 2020-12-11 00:25
Hi @jotoeri . thank you very much. sorry i was reading the main issue page and scrolling few page and couldn't find the same purpose feature request. Glad to hear its coming on v2.1. now i will learn to use the manual quick fix. tqvm
