### ISSUE TITLE
URLs in questions aren't clickable or selectable

### ISSUE THREAD

**Issue by lzmartinico** [nextcloud/forms#1414] opened 2022-11-24 18:10 UTC
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
When a URL is present on a form question, it's not properly parsed as a URL, and therefore it is not clickable. Additionally, since text is not selectable, it can't be copied and pasted, forcing people to type the whole URL out.

**To Reproduce**
1. Make a new form
2. Add a new question
3. Insert any URL in the question's text
4. Post form

**Expected behavior**
URLs should be clickable

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 25.0..1
- Forms-Version: 3.0.1

**Desktop (please complete the following information):**
 - OS: any
 - Browser: tested with Chromium and Firefox
 - Version: 107

**Comment by Chartman123** [comment] 2022-11-24 19:59
Duplicate of #1253

**Closed by Chartman123** 2022-11-24 19:59 UTC
Labels: bug, 0. Needs triage

**Comment by lzmartinico** [comment] 2022-11-25 01:51
It looks like #1253 refers to having links in the description, while my issue was about links in questions. But I guess the solution for the two issues would be the same, so I am OK for this to be closed, just as long as the fix gets applied to both parts of the form

**Comment by Chartman123** [comment] 2022-11-25 07:24
@lzmartinico Yes, this will be tackled by the same PR 👍🏻
