### ISSUE TITLE
Send E-mail Alert to new Answer

### ISSUE THREAD

**Issue by Gustavo-FS** [nextcloud/forms#649] opened 2020-10-23 14:03 UTC
**Nextcloud (please complete the following information):**
- Nextcloud-Version: [e.g. 19.0.0] : 20.0.0
- Forms-Version: [e.g. 2.0.0-beta4] Last Version

**Is your feature request related to a problem? Please describe.**
It´s possible send a automatic e-mail when a new Answers its Submited

**Comment by skjnldsv** [comment] 2020-10-25 14:24
Duplicate of https://github.com/nextcloud/forms/issues/12

**Closed by skjnldsv** 2020-10-25 14:24 UTC
Labels: duplicate, enhancement
