### ISSUE TITLE
scale questions from 1 to 10

### ISSUE THREAD

**Issue by mokkin** [nextcloud/forms#426] opened 2020-05-29 20:31 UTC
It should be possible to use scale questions from 1 to 10 like in LimeSurvey:
https://forums.limesurvey.org/forum/can-i-do-this-with-limesurvey/117505-10-point-scale-question

**Comment by jotoeri** [comment] 2020-05-29 20:38
Closing as duplicate of #356
Please next time search for open issues and use the given template on a request.

**Closed by jotoeri** 2020-05-29 20:38 UTC
Labels: 0. Needs triage, enhancement
