### ISSUE TITLE
Add "other" field

### ISSUE THREAD

**Issue by Sdighi** [nextcloud/forms#743] opened 2021-01-19 12:27 UTC
with google form you can add an 'other' field that allows you to write an answer. is it possible here too?

**Comment by Sdighi** [comment] 2021-01-19 16:13
![tempsnip](https://user-images.githubusercontent.com/68104445/105061284-a32b5200-5a79-11eb-85ee-3e6a7b9d3c0b.png)

**Comment by jotoeri** [comment] 2021-01-19 16:15
Duplicate of #93. 😉

**Closed by jotoeri** 2021-01-19 16:15 UTC
