### ISSUE TITLE
This is still showing in footer: "Get your own free account"

### ISSUE THREAD

**Issue by taziobaker** [nextcloud/forms#1751] opened 2023-10-20 16:37 UTC
**Describe the bug**
In our NC installation we set 'simpleSignUpLink.shown' => false, in the config.php. Other apps like Appointments share forms without the "Get your own free account". Unfortunately they still have the index.php in the URL, luckily which you do not.

**To Reproduce**
Any form shared link visited shows the footer link.

**Expected behavior**
Removing the footer as indicated in the config.php file.

**Screenshots**

**Nextcloud (please complete the following information):**
- Nextcloud-Version: [27.1.2]
- Forms-Version: [3.3.1]

**Desktop (please complete the following information):**
 This is OS, browser and version independent 

**Smartphone (please complete the following information):**
 This is Mobile, OS, browser and version independent

**Additional context**

**Comment by Chartman123** [comment] 2023-10-20 22:16
@taziobaker This is probably related to your installation. I cannot reproduce this at all. As soon as I add this parameter and reload the page, the sign-up link disappears in the footer. Please double-check your config and installation :)

**Comment by taziobaker** [comment] 2023-10-24 00:46
I installed through HestiaCP with their Quick Install... I'm regretting it so much.

**Comment by Chartman123** [comment] 2023-10-24 06:18
Ok, you can try to get more help for that on help.nextlcoud.com :) For now, I'll be closing this issue here.

**Closed by Chartman123** 2023-10-24 06:18 UTC
Labels: bug, 0. Needs triage, needs info
