### ISSUE TITLE
Copy-Paste-Issues

### ISSUE THREAD

**Issue by gohrner** [nextcloud/forms#1561] opened 2023-03-16 20:49 UTC
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
Pasted text just disappears, see attached screencast.

**To Reproduce**
1. In a form in edit mode, go to a description field with some text
2. Paste any text after the existing text.
3. Click outside of the description field.
4. The pasted text will disappear.

**Expected behavior**
The pasted text should not disappear.

**Screenshots**
![Peek 2023-03-16 21-46](https://user-images.githubusercontent.com/26199042/225749148-0dc98842-1f40-4c9f-8b1f-57f9f9b1627a.gif)

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 25.0.4
- Forms-Version: 3.2.0

**Desktop (please complete the following information):**
 - OS: KDE neon (Ubuntu 22.04)
 - Browser: Chromium
 - Version 111.0.5563.64 (Offizieller Build) Built on Ubuntu , running on neon 22.04 (64-Bit)

**Comment by Chartman123** [comment] 2023-05-13 18:15
I cannot reproduce this behaviour with our current main branch. So this will probably automatically fixed with the next app version.

**Closed by Chartman123** 2023-05-13 18:15 UTC
Labels: bug, 0. Needs triage
