### ISSUE TITLE
Public access is not real public, still need to sign in

### ISSUE THREAD

**Issue by alexwyl** [nextcloud/forms#232] opened 2020-03-18 02:22 UTC
Firstly, thanks for your good work!, and I don't know if this is a issue.

**Which Forms version are you running?** (see apps page)
1.1.1
**Nextcloud or ownCloud?:**
Nextcloud 
**Nextcloud/ownCloud version:** (see Nextcloud admin page)
18.02
### Steps to reproduce
1. Create a form with public access;
2. Copy the link to clipboard, and paste it to another web browser without signing in nextcloud;

### Actual behaviour
Get this message :
Internal Server Error

The server was unable to complete your request.
If this happens again, please send the technical details below to the server administrator.
More details can be found in the server log.
Technical details

Remote Address: XXX.XXX.XXX.XXX
Request ID: 2Y8MiB1myEIUc6BpBmL7

### Expected behaviour
To show the form.

**Comment by Saik0Shinigami** [comment] 2020-03-18 06:37
I am seeing the same issue. 
Only difference from above is I can validate this occurs on Nextcloud 18.01 

Checking the logs themselves I see:

[index] Error: Exception: Argument 2 passed to OCA\Forms\Db\NotificationMapper::findByUserAndForm() must be of the type string, null given, called in /var/www/nextcloud/apps/forms/lib/Controller/PageController.php on line 277 at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 125
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Forms\Controller\PageController {}, "gotoForm")
1. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Forms\\Controller\\PageController", "gotoForm", OC\AppFramework\ ... {}, {hash: "8DvkBKeA ... "})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({hash: "8DvkBKeA ... "})
3. /var/www/nextcloud/lib/private/Route/Router.php line 299
   call_user_func(OC\AppFramework\ ... {}, {hash: "8DvkBKeA ... "})
4. /var/www/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/apps/forms/form/8DvkBKeAEZVcBf8I")
5. /var/www/nextcloud/index.php line 38
   OC::handleRequest()

GET /apps/forms/form/8DvkBKeAEZVcBf8I
from 10.10.2.110 at 2020-03-17T23:00:01-07:00

**Comment by jotoeri** [comment] 2020-03-18 10:02
Its true, this is a bug. @githubDante tackled it already in #195.

Anyway i close this one as duplicate of #178 ;)

**Closed by jotoeri** 2020-03-18 10:02 UTC
