### ISSUE TITLE
Send response via e-mail

### ISSUE THREAD

**Issue by hansimausisteffiwurstbrot** [nextcloud/forms#1233] opened 2022-06-29 19:34 UTC
**Is your feature request related to a problem? Please describe.**
It's imho quite a long way with several clicks in order to get to the responses.
[OT: even longer as forms can't be shared and we have to switch accounts in order to access the responses]

It would be really useful to have an option to receive an e-mail -including the responses- every time someone enters a form.

**Comment by jotoeri** [comment] 2022-06-30 06:05
Duplicate of #883 
Please search for existing issues before opening a new one. 😉

**Closed by jotoeri** 2022-06-30 06:05 UTC
Labels: enhancement, 0. Needs triage

**Comment by hansimausisteffiwurstbrot** [comment] 2022-07-04 19:20
> Duplicate of #883 Please search for existing issues before opening a new one. 😉

Yeah, I searched plenty and as the linked topic is about a PDF I opened up a new one.

We don't need a PDF, just the responses in plain text within the e-mail...

I guess it's different, isn't it?

@jotoeri please open it again. :)

**Comment by jotoeri** [comment] 2022-07-05 13:11
Well, tbh. i don't see us implementing two ways currently. And then the pdf is most probably the way to go.
Anyways - if somebody wants to implement it, i'm not standing in the way. 🤷‍♂️

**Comment by violoncelloCH** [comment] 2022-09-18 16:15
maybe a duplicate of #525 ?

**Comment by Chartman123** [comment] 2022-09-18 16:48
> maybe a duplicate of #525 ?

Not exactly... This is for the creator of the form, the other one for the participant.

But implementing one will probably also help implementing the other.

**Comment by Prozesse** [comment] 2023-10-11 14:31
hey, I was searching for weeks for this thread. I have exactly the same issue as describes above. I use forms as a starting point of workflows for our school and it would be so great to have a trigger when someone submits a form to generate an E-Mail with the answer (i don't care if its PDF or text) sent to a specific adress or some kind of other implementation where the answers can be used further in a structured way. It's absolutely not practical to download the CVS everytime, if you work with the forms day to day and have around 10-20 anwers a day.

It would be even better, if I could connect a nextcloud-office-xlsx-file to the form and the answers show up in that file.
