### ISSUE TITLE
Feature request:  conditional fields

### ISSUE THREAD

**Issue by vincems** [nextcloud/forms#218] opened 2020-03-04 03:19 UTC
**Which Forms version are you running?** (see apps page)
1.0.3

**Nextcloud or ownCloud?:**
Nextcloud

**Nextcloud/ownCloud version:** (see Nextcloud admin page)
16.0.8

Couple of feature suggestions:

- conditional fields (along the lines of https://calderaforms.com/)
   All the parts are there. Great job btw.
   See here for an example of what I'm meaning by conditional forms.
         https://www.ostraining.com/blog/wordpress/conditional-logic-with-caldera-forms/

- Integration with nextcloud Work flow/todo.

**Comment by skjnldsv** [comment] 2020-04-29 16:32
Duplicate of #177

**Closed by skjnldsv** 2020-04-29 16:32 UTC
