### ISSUE TITLE
Releasing the mouse button outside text input will make the input lose focus

### ISSUE THREAD

**Issue by mschmidm** [nextcloud/forms#1667] opened 2023-07-05 18:29 UTC
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
If a user selects text within a text input, such as the description input, and releases the mouse button outside the input, the input loses its focus and the text selection fails.
For the description input, it is necessary to move the mouse outside of the input. 
For question inputs, the mouse has to be moved outside of the entire question element.

**To Reproduce**
1. Create a new form
2. Type something in the description
3. Try to select the text but release the mouse button outside the description input
4. The input loses focus and the text selection fails

**Expected behavior**
The input should not lose focus and the text should be selected. This is the behavior of any normal HTML input and makes text selection easier because the user does not have to be very precise with the mouse.

**Nextcloud**
- Nextcloud-Version: 26.0.2
- Forms-Version: 3.3.1

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Version:  114.0.5735.198
 
Thank you very much for your work on Forms, it's a really nice app! :)

**Comment by Chartman123** [comment] 2023-07-05 20:46
Duplicate of #1565

**Closed by Chartman123** 2023-07-05 20:46 UTC
Labels: bug, 0. Needs triage
