### ISSUE TITLE
Nextcloud Forms

### ISSUE THREAD

**Issue by Pizdecovi4** [nextcloud/forms#2425] opened 2024-11-21 15:51 UTC
**Nextcloud (please complete the following information):**

-   Nextcloud-Version: [e.g. 19.0.0]
-   Forms-Version: [e.g. 2.0.0-beta4]

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Hi!

Dear developers, I ask you to add: 
1) the ability to flexibly configure the sending of form results to certain emails 
2) Enable the ability to send the result to the person who filled out the form by e-mail. 
3) Add the option of automatically printing the email address of the person who fills out the letter to the form parameters, after which it can be automated in jira and other service centers. A separate field where, when filled in, it will already be test@example.com (Test is the user who fills out the form) 

It would be convenient to use this.

**Comment by Chartman123** [comment] 2024-11-22 09:13
Hi @Pizdecovi4 

thanks for your feedback. The next time, please use our template, it's there for a reason. Also please use the search before creating a new issue. Here are my comments:

> * the ability to flexibly configure the sending of form results to certain emails

Duplicate of #1810

> * Enable the ability to send the result to the person who filled out the form by e-mail.

Duplicate of #525 

> * Add the option of automatically printing the email address of the person who fills out the letter to the form parameters, after which it can be automated in jira and other service centers. A separate field where, when filled in, it will already be [test@example.com](mailto:test@example.com) (Test is the user who fills out the form)

This can't be done in a reliable way: for publicly shared forms there is no user available.

So I'll close this issue as duplicate/won't fix.

**Closed by Chartman123** 2024-11-22 09:13 UTC
Labels: enhancement, 0. Needs triage
