### ISSUE TITLE
Missing feedback on loading form share link

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/forms#448] opened 2020-06-09 10:23 UTC
If you go to the share link of a form, for some seconds you see the header and footer only, with just a blank content until the form loads.

Instead we should show a simple emptycontent loading feedback like:

> (Loading spinner)
> Loading form …

For more advanced loading feedback, a skeleton screen would also be nice (like we do in Talk and the mobile apps).

![Forms loading feedback](https://user-images.githubusercontent.com/925062/84136703-f7824400-aa4b-11ea-93fe-91a3ac40a685.png)

**Comment by susnux** [comment] 2022-10-26 13:40
Can you reproduce this with NC25 and 3.0.1?
As I can not, it looks like the form is included in the first data sent by the server for the public share.
So no loading happens after the page was rendered.

**Comment by Chartman123** [comment] 2023-06-23 16:55
@jancborchardt Is this still valid? I couldn't reproduce it either...

**Comment by Chartman123** [comment] 2023-12-11 10:20
No feedback, closing as no longer valid

**Comment by Chartman123** [comment] 2023-12-11 11:11
I can reproduce it on a relatively slow connection... first the public page layout is rendered including the footer, but without any content. Then it takes some time until the actual form is rendered.

**Comment by Chartman123** [comment] 2024-04-14 16:03
@susnux I had another look at this... I think that you were right with your [comment](https://github.com/nextcloud/forms/issues/448#issuecomment-1292067487) earlier. So I think we can indeed close this.

**Closed** 2024-04-15 14:02 UTC
Labels: bug, 1. to develop, design, feature: 📝 submitting responses
