### ISSUE TITLE
Section header

### ISSUE THREAD

**Issue by welrbraga** [nextcloud/forms#1831] opened 2023-12-13 14:12 UTC
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 25.0.12
- Forms-Version: 3.3.1

**Is your feature request related to a problem? Please describe.**
Long forms are tedious to read and answer. It should be nice if we had a way to separate and group questions in sections, according to the subject.

For example in a avaluate form sent to students of a hypothetical dev course, I could have a section with "personal questions", followed by another section with "course evaluation" and just below a third section with questions to evaluate the instructor.

**Describe the solution you'd like**
Nowadays, every question type requires at least one option or show a text box. IMHO I think, it is simple to implement this feature like a question type without answers that should be exhibited with a different "css" to destak a begin of new section.
Maybe, to keep CSV design simple, it should be only a empty field ignored on statistic screen.

**Describe alternatives you've considered**
Another option I thought should be a pagination feature but, certainly, it is more complex to implement. 
Maybe It should be another resource to implement in a future.

**Comment by Chartman123** [comment] 2023-12-13 14:45
Duplicate of #624 

Please use the search function before creating new issues

**Closed by Chartman123** 2023-12-13 14:45 UTC
Labels: duplicate, enhancement
