### ISSUE TITLE
Using iphone and safari

### ISSUE THREAD

**Issue by DaOsmo76** [nextcloud/forms#625] opened 2020-10-07 08:40 UTC
Nextcloud: 19.0.3
Forms: 	   2.0.4

When creating a form and non users of the cloud clicks on the provided link they only get directed to login page.
Only happens to people that get sent the link and opening this form on iphone and safari.

**Comment by jotoeri** [comment] 2021-02-10 15:31
@violoncelloCH afaik you are iOS user? Can you confirm this? Unfortunately i have no device to test it. :(

**Comment by violoncelloCH** [comment] 2021-02-11 15:51
@jotoeri I'm not, sorry... My sister uses one, that's where I test this kind of things from time to time... let me see if I find some time with her to test this issue...

**Comment by jotoeri** [comment] 2021-02-11 22:27
Oh, ok. So don't worry then if you dont find the time... 👍

**Comment by idecable** [comment] 2021-02-28 16:54
I have a workaround that works, see my post on https://github.com/nextcloud/forms/issues/523

**Comment by jotoeri** [comment] 2021-02-28 17:17
@idecable please read the original post here. This is a different topic, than the zooming thing. However as it seems you are an iphone user - Can you confirm this issue here? Can you reproduce this problem? 😉 🙈 
> non users of the cloud clicks on the provided link they only get directed to login page. Only happens to people that get sent the link and opening this form on iphone and safari.

**Comment by idecable** [comment] 2021-02-28 17:59
> @idecable please read the original post here. This is a different topic, than the zooming thing. However as it seems you are an iphone user - Can you confirm this issue here? Can you reproduce this problem? 😉 🙈
> 
> > non users of the cloud clicks on the provided link they only get directed to login page. Only happens to people that get sent the link and opening this form on iphone and safari.

My bad I removed my comment. That was indeed for a different issue.


I am unable to reproduce.

**Comment by jotoeri** [comment] 2021-02-28 18:34
@idecable No problem, thank you! 😉 

@DaOsmo76 are you still able to reproduce your problem? Are you able to update your cloud to the latest patch of NC19 and/or forms to the current version 2.1 and check again?

**Comment by DaOsmo76** [comment] 2021-02-28 19:18
Not right now.
I send form links to different group of users, but have not since december.

To make clear, the issue is that certain iPhone users (do not now which ios
version) contact me that they get sent to login page even if the form is a
public link.



Den sön 28 feb. 2021 19:34Jonas <notifications@github.com> skrev:

**Comment by jotoeri** [comment] 2021-02-28 20:07
Hm, ok. So i'd close this issue for now, íf we can't reproduce. Feel free to re-open it, in case you can reproduce it and give us a bit more details about the device. :)

Greets! :)
Jonas

**Closed by jotoeri** 2021-02-28 20:07 UTC
Labels: 0. Needs triage, bug
