### ISSUE TITLE
Ability to share editing of forms and results with others

### ISSUE THREAD

**Issue by audunmb** [nextcloud/forms#1118] opened 2022-02-11 14:53 UTC
If I create a form, only I can edit it and see the results. My coworkers can only fill out the form, not view/download results and edit the form. There should be an option to allow others full access, by group or individually. 

I couldn't find any solution or open issue on this, please let me know if this is already possible.

**Comment by jotoeri** [comment] 2022-02-11 22:21
Duplicate of #322
Please search for existing issues before opening a new one. ;)

**Closed by jotoeri** 2022-02-11 22:21 UTC
Labels: enhancement, 0. Needs triage
