### ISSUE TITLE
Forms effectively disappeared in Nextcloud 28

### ISSUE THREAD

**Issue by bernd-wechner** [nextcloud/forms#1882] opened 2024-01-18 11:07 UTC
**Describe the bug**
I upgraded my server to Nextcloud 27 then 28 ... bit of a catch up, and am exploring it, and find Forms have effectively disappeared. By which I mean they are still installed, I see it under installed Apps, I see the button on the top menu:

![image](https://github.com/nextcloud/forms/assets/7296506/5f0c1958-c2c4-4d42-822d-729c7d710a0d)

and I see it on the Administration menu list:

![image](https://github.com/nextcloud/forms/assets/7296506/344339cd-b395-4e65-9d4f-a93d2c6c08ae)

But if I click the top menu button I am greeted with a lovely background cloud image. If I click the Administration menu button I am greeted with a white page. No errors, no feedback, and nothing in the nextcloud.log file in the data dir to lend any clues alas.

**Nextcloud (please complete the following information):**
- Nextcloud-Version: [Nextcloud Hub 7](https://nextcloud.com/) (28.0.1)
- Forms-Version:[4.0.0

**Desktop (please complete the following information):**
 - OS:  Kernel: 5.15.0-91-generic x86_64 bits: 64 Console: pty pts/3,  Distro: Ubuntu 22.04.3 LTS (Jammy Jellyfish)
 - Browser: Firefox
 - Version 121

**Browser log**
No errors there, when I click the top menu button to be greeted with na empty page, two warnings are issued:

```
21:51:33.544 Loading failed for the module with source “https://my.nextcloud.server/apps/forms/js/forms-main.mjs?v=6a77da55-0”. [forms:33:206](https://my.nextcloud.server/index.php/apps/forms/)
21:51:34.897 Proxying an event bus of version 3.1.0 with 1.3.0 [index.es.js:2337:14](webpack:///notifications/node_modules/@nextcloud/notify_push/node_modules/@nextcloud/auth/node_modules/@nextcloud/event-bus/dist/index.es.js)
```
​The first is mildly interesting but not very informative. If I click the ling to the module source, that downloads and opens in atext editor,, and if I click on the line number it takes me to this source line:

```
<script nonce="VWJxNkFsSCtLRVh4bUwrTjV6cXlabmo0T3lHd2ZCT1libythenBibTcyQT06SStqMVdoZTZHaDNJd1AyMXRFdUNWVW1QVUhtQlR5YlVHYnFqNWNTVnFDRT0=" defer src="/apps/forms/js/forms-main.mjs?v=6a77da55-0" type="module"></script>
```

**Additional context**
Logging is also broken, and presents a white page when clicked on the administration window even though nextcloud.log is in the data dir, and is collecting lines as I play ... Likewise no errors on the console, and probably an unrelated issue, with similar symptom.

The server looks clean:

![image](https://github.com/nextcloud/forms/assets/7296506/f55aa9d9-3bdc-4214-b25f-4a50b942fbad)

```
$ occ status
  - installed: true
  - version: 28.0.1.1
  - versionstring: 28.0.1
  - edition: 
  - maintenance: false
  - needsDbUpgrade: false
  - productname: Nextcloud
  - extendedSupport: false
$ occ setupchecks
	dav:
		✓ DAV system address book: No outstanding DAV system address book sync.
	system:
		⚠ Errors in the log: 1 error in the logs since January 11, 2024
		ℹ Brute-force Throttle: Your remote address could not be determined.
		✓ File locking
		✓ Memcache: Configured
		✓ PHP modules
		✓ Architecture: 64-bit
	notifications:
		✓ Push notifications - Fair use policy
	security:
		✓ Old user imported certificates
		ℹ Forwarded for headers: Your remote address could not be determined.
		✓ Old server-side-encryption: Disabled
		✓ PHP version: You are currently running PHP 8.1.2-1ubuntu2.14.
		✓ Random generator: Secure
	database:
		✓ Database missing columns: None
		✓ Database missing indices: None
		✓ Database missing primary keys: None
		✓ Database version: 14.10 (Ubuntu 14.10-0ubuntu0.22.04.1)
		✓ Database transaction isolation level: Read committed
	config:
		✓ Default phone region: AU
		✓ Email test: Email test was successfully sent
		✓ Configuration file access rights: Nextcloud configuration file is writable
	network:
		✓ Internet connectivity
	php:
		✓ PHP default charset: UTF-8
		✓ Freetype: Supported
		✓ PHP getenv
		✓ PHP memory limit: ?
		✓ PHP "output_buffering" option: Disabled
```

Bit stuck ... how to further diagnose? Such silent failure is puzzling and not particularly thrilling ;-)

**Comment by Chartman123** [comment] 2024-01-18 12:08
@bernd-wechner please use the search function before creating new issues... we had this problem only yesterday.

Duplicate of #1838

**Closed by Chartman123** 2024-01-18 12:08 UTC
Labels: bug, 0. Needs triage

**Comment by bernd-wechner** [comment] 2024-01-18 20:15
I did check, but not find. Be careful with presumptions. But alas, it seems I did not look successfully or very well ;-).
