### ISSUE TITLE
Provide the Option to edit form by sharing with a user or group

### ISSUE THREAD

**Issue by timmwille** [nextcloud/forms#1946] opened 2024-02-09 13:42 UTC
**Nextcloud (please complete the following information):**
- Nextcloud-Version: latest stable
- Forms-Version: latest stable

**Is your feature request related to a problem? Please describe.**
For a lot of situations a form has to be designed and managed by multiple users/a working-group.

**Describe the solution you'd like**
Would be great to have a sharing option that allows also editing of the form

**Describe alternatives you've considered**
currently one has to setup a dummy account to manage the forms (sharing the access to results from there is possible, thank you for that, it already helps a lot).

**Additional context**
Might be added together with #617 #1945 - i could not find a matching issue, but might have overlooked, please link if I created a duplicate

**Comment by Chartman123** [comment] 2024-02-11 10:15
Duplicate of #322

**Closed** 2024-02-11 10:15 UTC
Labels: enhancement, 0. Needs triage
