### ISSUE TITLE
Feature Request: Upload files

### ISSUE THREAD

**Issue by boydhako** [nextcloud/forms#131] opened 2019-11-30 03:32 UTC
Not entirely sure where to submit feature requests for this app. But, it'd be nice if it had the ability for one to upload files like the Google Forms allows.

Scenario Example:
One uses a "private" form to create a record of things done and needs to attach pictures or documents of things to reference or document.

**Comment by luixxiul** [comment] 2019-12-01 21:12
duplicate of https://github.com/nextcloud/forms/issues/42?

**Comment by luixxiul** [comment] 2020-01-15 16:36
Closing as duplicate #42

**Closed by luixxiul** 2020-01-15 16:36 UTC
Labels: duplicate
