### ISSUE TITLE
Feature Request Translations + Validation

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/forms#1276] opened 2022-08-03 07:38 UTC
It would be great if you could store translations for the field labels, so that depending on the browser language the label of the fields is adapted.

Furthermore it would be cool if you could include field validation with e.g.: Regex to guarantee password length and complexity or correctness of email addresses.

**Comment by jotoeri** [comment] 2022-08-03 07:51
Duplicate of #269 and #177 
Please search for existing issues before opening a new one.

**Closed by jotoeri** 2022-08-03 07:51 UTC
