### ISSUE TITLE
long text export

### ISSUE THREAD

**Issue by ROFLdld** [nextcloud/forms#1422] opened 2022-12-13 20:59 UTC
When exporting results to CSV from forms with "Long Text" questions, they only export the first line of the text entered. For example, listing names of people attending like:

First First
Second Second

The CSV file will only list First First under that field.

Thanks!

**Comment by jotoeri** [comment] 2022-12-14 11:01
Duplicate of #683
Please see https://github.com/nextcloud/forms/issues/683#issuecomment-727578019

**Closed by jotoeri** 2022-12-14 11:01 UTC
Labels: bug, 0. Needs triage
