### ISSUE TITLE
Create new type of ansswer: Upload files

### ISSUE THREAD

**Issue by Iwios** [nextcloud/forms#1681] opened 2023-08-04 15:35 UTC
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 27.0
- Forms-Version: [3.3.0]

**Is your feature request related to a problem? Please describe.**
I would need to be able to create a question with the ability to send a file to a nextcloud folder

Thank for your time :)

**Comment by Chartman123** [comment] 2023-08-04 17:14
Duplicate of #42

**Closed** 2023-08-04 17:15 UTC
Labels: enhancement, 0. Needs triage

**Comment by Piefje01** [comment] 2023-08-24 12:05
I'm surprised that the upload function in FORMS is still not there. Do we still have to go to google docs? The discussion of whether it is trusted (virus) etc. is something the user should consider whether or not to use the option. Forms in nextcloud is another app with good intentions but not finished at all.

**Comment by Chartman123** [comment] 2023-08-24 12:15
Hi @Piefje01 

Thanks for your offer to work on this :) We're open source and always glad that someone wants to step up and start collaborating.
