### ISSUE TITLE
Multi-pages form

### ISSUE THREAD

**Issue by s8321414** [nextcloud/forms#1695] opened 2023-08-21 04:11 UTC
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 27.0.1
- Forms-Version: 3.3.1

**Is your feature request related to a problem? Please describe.**
Some forms design require split multi questions to multi pages, but we don't have this feature.

**Describe the solution you'd like**
Add a feature to split a form into multi pages.

**Comment by Chartman123** [comment] 2023-08-21 05:54
Duplicate of #357

**Closed** 2023-08-21 05:54 UTC
Labels: enhancement, 0. Needs triage
