### ISSUE TITLE
Transfer Ownership not possible

### ISSUE THREAD

**Issue by michaelortnersanube** [nextcloud/forms#1960] opened 2024-02-14 14:44 UTC
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
Not possible to transfer ownership. 

**To Reproduce**
1. Go to 'Forms'
2. Click on 'Share'
3. Click on Settings
4. Transfer Ownership

**Expected behavior**
Text which should display what i have to insert.

**Screenshots**
![image](https://github.com/nextcloud/forms/assets/96595501/d370ef63-91ff-48e9-8a4e-4b0dda8ceec9)

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 28.0.2
- Forms-Version: 4.1.0

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome, safari 
 - Version 17.2.1 (safari)

**Browser log**
[Error] Failed to load resource: the server responded with a status of 404 ()
[Error] Failed to load resource: the server responded with a status of 404 ()
[Error] Failed to load resource: the server responded with a status of 404 () (
[Error] Failed to load resource: the server responded with a status of 404 () (mh
[Error] Failed to load resource: the server responded with a status of 404 () (Mich
[Error] Failed to load resource: the server responded with a status of 404 () (Michae
[Error] Failed to load resource: the server responded with a status of 404 () (Micha
[Error] Failed to load resource: the server responded with a status of 404 () (Mich
[Error] Failed to load resource: the server responded with a status of 404 () (Mic
[Error] Failed to load resource: the server responded with a status of 404 () (M
[Error] Failed to load resource: the server responded with a status of 404 () (
[Error] Failed to load resource: the server responded with a status of 404 () 
[Error] Failed to load resource: the server responded with a status of 404 () (
[Error] Failed to load resource: the server responded with a status of 404 () 
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

I have removed the names because of DSGVO!
```

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by Chartman123** [comment] 2024-02-15 08:00
Duplicate of #1956

**Closed by Chartman123** 2024-02-15 08:00 UTC
Labels: duplicate
