### ISSUE TITLE
Cannot edit form on mobile device in portrait mode

### ISSUE THREAD

**Issue by tmlmt** [nextcloud/forms#2145] opened 2024-05-07 04:54 UTC
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
I cannot edit a Form on my mobile device in Portrait mode.

**To Reproduce**
1. Go to a form with your mobile in Portrait mode
2. Click on any text input field
3. Observe that you can't edit the field
4. Turn your mobile into Landscape mode
5. Try again and see that you can now edit fields 

**Expected behavior**
I expect the form to be editable in any orientation  

**Screencast**
https://github.com/nextcloud/forms/assets/10244927/5797d4d0-52a4-4b3b-8000-3fd91457313f

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 29.0.0
- Forms-Version: 4.2.3

**Smartphone (please complete the following information):**
- Device: iPhone 13
- OS: iOS 17.4.1
- Browser: Chrome 124.0.6367.111 and Brave 1.65

**Browser log**
```

DEBUGUnified search initialized!
DEBUGSearch providers [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
DEBUGInitializing unified search plugin-filters from talk
INFOsession heartbeat polling started
DEBUGContacts [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
DEBUGRegistering notifications container as a menu
INFOBrowser does not support notifications
DEBUGPolling interval updated to 30000
DEBUGStarted background fetcher as session_keepalive is enabled
DEBUG[DEBUG] core: this browser is officially supported ! 🚀 [object Object]
DEBUGGot notification data, restoring default polling interval.
DEBUG[DEBUG] forms: Loading form 2 [object Object]
```

**Comment by susnux** [comment] 2024-05-08 22:14
Duplicate of #2139 both caused by screen width issues on mobile devices

**Closed by susnux** 2024-05-08 22:14 UTC
Labels: bug, 0. Needs triage
