### ISSUE TITLE
Internal share link opens an empty page if I haven't used forms app before

### ISSUE THREAD

**Issue by akhil1508** [nextcloud/forms#1893] opened 2024-01-24 12:16 UTC
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
- This is about the internal share link feature to share to logged in users
- When I have never used the forms app before and I use the internal share link, I cannot access the form and submit

**To Reproduce**
1. Create a form as a nextcloud user
2. Create an internal share link from the right hand side share dialog
3. Copy internal share link
4. Login as another nextcloud user
5. Paste internal share link in address bar of browser and click enter
6. The form doesn't load up

**Expected behavior**
- The form that was shared has to show up

**Screenshots**
![image](https://github.com/nextcloud/forms/assets/14362579/84984dc4-1070-493c-999e-1b55d7851f55)
![image](https://github.com/nextcloud/forms/assets/14362579/c0b0c2f8-9d0f-4fdd-ab37-a2e655ac1011)

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 26.0.8
- Forms-Version: 3.4.4

**Additional context**

**Comment by Chartman123** [comment] 2024-01-24 12:38
Duplicate of #1779

**Closed by Chartman123** 2024-01-24 12:38 UTC
Labels: bug, 0. Needs triage
