### ISSUE TITLE
Install failure of Forms 4.3.2

### ISSUE THREAD

**Issue by mwreimer** [nextcloud/forms#2402] opened 2024-11-07 16:10 UTC
**Describe the bug**
Install of Forms 4.3.2 from the App Store of Nextcloud Hub 7 (28.0.12) fails with error:

**An error occurred during the request. Unable to proceed.
Primary index name "id" for table "oc_forms_v2_uploaded_files" collides with the constraint on table "oc_e2e_encryption_lock**

**To Reproduce**

1. In the Nextcloud AppStore, select Featured apps, and find the Forms app
2. Click on "Download and enable".
3. See the above error.

**Expected behavior**
Successful install of the Forms app.

**Screenshots**
![Image](https://github.com/user-attachments/assets/4cce73ed-5802-430c-97fa-4efb350b5137)

**Nextcloud (please complete the following information):**

-   Nextcloud-Version: [Nextcloud Hub 7](https://nextcloud.com/) (28.0.12)
-   Forms-Version: 4.3.2 

**Desktop (please complete the following information):**

-   OS: Linux, Ubuntu 22.04
-   Browser: Firefox 
-   Version: 132.0.1

**Additional context**

In the Nextcloud database, the table "oc_forms_v2_uploaded_files" does not exist.

Table oc_e2e_encryption_lock is empty:

mysql> select * from oc_e2e_encryption_lock;
Empty set (0.00 sec)

**Comment by Chartman123** [comment] 2024-11-07 20:31
Duplicate of #2346 

Please use the search before opening new issues :)

**Closed by Chartman123** 2024-11-07 20:31 UTC
Labels: bug, 0. Needs triage
