### ISSUE TITLE
allow sharing form results

### ISSUE THREAD

**Issue by KiaraGrouwstra** [nextcloud/forms#1323] opened 2022-09-02 22:06 UTC
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 24.0.3
- Forms-Version: 2.5.1

**Is your feature request related to a problem? Please describe.**
I would like to share submissions to a form with a colleague.

**Describe the solution you'd like**
An option to share not just the ability to fill or edit a form, but also access its live results.

**Describe alternatives you've considered**
Sharing a static copy of results.

**Additional context**
#5 could address this as well, but that one might be more involved.

**Comment by Chartman123** [comment] 2022-09-03 18:00
Duplicate of #455

**Closed** 2022-09-03 17:59 UTC
Labels: enhancement, 0. Needs triage
