### ISSUE TITLE
Shared forms not shown to users they are shared with

### ISSUE THREAD

**Issue by gitbrasser** [nextcloud/forms#563] opened 2020-08-18 16:19 UTC
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
When I make a form as user A and share it with either user B or a group that user B is part of, the form does not show up in the environment of user B. Not in the app 'Forms', neither as announcement.

Maybe it is behaviour as designed but I cannot find a document that explains how to share the form so it shows up.
Sharing by link (copy the link as user A and open the link as user B) works though.

**To Reproduce**
1. As user A,, go to app 'Forms'
2. Click on 'New form'
3. Giveit a title, yadayadayada
4. Toggle settings so you can share form
5. Choose users to share with
6. Choose user B, or group user B is member of.
7. As user B, go to app 'Forms'
8. Find no new forms created by other users.

Forms created by user B and shared with user A are also not shown in the environment of user A.

**Expected behavior**
User B would see the form that was just created and shared by user A.

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 19.0.1
- Forms-Version: 2.0.2

**Desktop (please complete the following information):**
 - Browser user A: Chrome. Browser user B: firefox.

**Comment by skjnldsv** [comment] 2020-08-19 08:40
Duplicate of #322

**Closed by skjnldsv** 2020-08-19 08:40 UTC
Labels: 0. Needs triage, bug
