### ISSUE TITLE
Limit access in case of anonymous voting

### ISSUE THREAD

**Issue by scroom** [nextcloud/forms#896] opened 2021-04-13 20:35 UTC
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 19.0.8
- Forms-Version: 2.2.4

**Is your feature request related to a problem? Please describe.**
We would like to use Nextcloud Polls for voting. However, we have the problem that polls have to be anonymous according to our bylaws. Nevertheless, we don't want anyone to vote more than once or that the voting link is passed on to external parties. 

**Describe the solution you'd like**
Therefore, it would be great if there would be some kind of TAN generator or similar, through which I could determine the number of people voting and get a list of TANs issued, which I could then distribute to those who are authorized.

**Comment by jotoeri** [comment] 2021-04-14 10:15
Hey @scroom,
just to be sure, as you are talking about polls: There is a specific polls app for nextcloud, separate of this forms-app. Is your request for the forms-app or for the polls-app?
In case it's forms, i'd close it as duplicate of #617?! 😉 

Greets,
Jonas

**Closed** 2021-04-21 13:28 UTC
Labels: 0. Needs triage, enhancement, needs info
