### ISSUE TITLE
Feature Request: 5 point choice or bar

### ISSUE THREAD

**Issue by JtheBAB** [nextcloud/forms#1044] opened 2021-09-17 10:11 UTC
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 21.0.4
- Forms-Version: 2.3.0

**Is your feature request related to a problem? Please describe.**
I would like to create a form where students can self evaluate how much they had understand the theory. I could do it with a DropDown but a 5 point choice or better a bar from 0-100% and then selecting the percentage would be more intuitive.

**Describe the solution you'd like**
A option to create a 5 point choice like [here](https://manual.limesurvey.org/Question_type_-_Array_(5_point_choice))
Or a bar where you can drag a slider to go to the percentage.

**Comment by jotoeri** [comment] 2021-09-17 19:51
Duplicate of #356 
Please search for existing issues before opening a new one. 😉

**Closed by jotoeri** 2021-09-17 19:51 UTC
Labels: enhancement, 0. Needs triage
