### ISSUE TITLE
The sharing link is not accessible via the iPhone browser

### ISSUE THREAD

**Issue by StevLauz** [nextcloud/forms#2166] opened 2024-05-13 19:00 UTC
Share link works for all platforms except iPhone browser,  Can you check this issue

**Comment by Chartman123** [comment] 2024-05-13 19:39
@StevLauz please tell us more about your installation and also which iOS version you are using. This is probably a duplicate

**Comment by StevLauz** [comment] 2024-05-13 19:52
You are right, it is indeed a duplicate of another form. I can't tell you which "iOS" version is used since it was iPhone users who reported the problem to me.

The NexCloud installation version is Nextcloud Hub 8 (29.0.0), Form version is 4.2.3

Envoyé depuis Proton Mail pour Android

-------- Message d'origine --------

**Comment by Chartman123** [comment] 2024-05-13 20:06
Please let them check if they are on iOS < 16.4

If so, it's probably this issue: https://github.com/nextcloud/forms/issues/2163

**Comment by StevLauz** [comment] 2024-05-13 21:39
Indeed it is the version iOS 15.8.2

Envoyé depuis Proton Mail pour Android

-------- Message d'origine --------

**Comment by Chartman123** [comment] 2024-05-13 21:41
Duplicate of #2163

**Closed by Chartman123** 2024-05-13 21:41 UTC
Labels: duplicate
