### ISSUE TITLE
Give other users the right to view/export the results

### ISSUE THREAD

**Issue by bademeister91** [nextcloud/forms#897] opened 2021-04-14 13:48 UTC
**Nextcloud (please complete the following information):**
- Nextcloud-Version: [16.0.0]
- Forms-Version: [1.0.3]

Give other users the right to view/export the results

**Comment by jotoeri** [comment] 2021-04-14 14:08
Duplicate of #455.
Please search for existing issues, before opening a new one. 😉

**Closed by jotoeri** 2021-04-14 14:08 UTC
Labels: 0. Needs triage, enhancement
