### ISSUE TITLE
Feature request for FORMS

### ISSUE THREAD

**Issue by TattyFromMelbourne** [nextcloud/forms#772] opened 2021-02-11 11:36 UTC
Hi beautiful people,

I would like to request a field type of "email". Basically it can function like a "short answer" field except that it has input validation (for an email.) 

Here is a use case:- we are asking people about some new (software) product or feature. The responses are anonymous but we want to offer the respondents a chance to provide us with their email so that, if they do, we can just dump to the answers to a CSV file  quickly add the email addresses to our mailing list to keep them notified about the next stage of our product or feature.

**Comment by jotoeri** [comment] 2021-02-11 12:01
Duplicate of #177.
Please search for existing issues before opening a new one!

**Closed by jotoeri** 2021-02-11 12:01 UTC

**Comment by TattyFromMelbourne** [comment] 2021-03-21 17:07
I did search for issues and do not understand why #499 (which is linked to #177) had the changes for email and telephone fields taken out again.

Please keep in mind that the email filed does not really need additional validation if you get the field type correct
i.e. the field should be 
```
<input type="email" ...>
```

( See ![image](https://user-images.githubusercontent.com/925062/88113333-dddb2d00-cbb1-11ea-8db3-3be4e817ba15.png) )
