### ISSUE TITLE
Allow text "Other" checkbox

### ISSUE THREAD

**Issue by jernst** [nextcloud/forms#543] opened 2020-08-04 15:20 UTC
We don't know what we don't know but often we'd like to find out. For example, I'd like to know your favorite fruit, so I create the following choices in my survey:

* Apple
* Orange
* Banana

But it turns out your favorite fruit is Star Fruit, something I had never heard of before. I cannot learn that this fruit exists and that you like it unless you can somehow specify it in my survey. So:

Please allow one of the selections in checkboxes / multiple choice / dropdown to be "other" with a text box into which the unexpected value can be filled in.

**Comment by skjnldsv** [comment] 2020-08-04 15:32
Hey! Thanks for your feedback, unfortunately, this is a
duplicate of #93

**Closed by skjnldsv** 2020-08-04 15:32 UTC
Labels: 0. Needs triage, enhancement

**Comment by jernst** [comment] 2020-08-04 15:33
Didn't see that, sorry.

**Comment by skjnldsv** [comment] 2020-08-04 15:34
No worries!! :)
Thank you for using Forms! :hugs:
