### ISSUE TITLE
New question type: Upload file or multiple files

### ISSUE THREAD

**Issue by biware-repo** [nextcloud/forms#771] opened 2021-02-09 09:38 UTC
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 20.0.0 and higher
- Forms-Version: where is it possible

**Is your feature request related to a problem? Please describe.**
Sometime employees need upload some documents with some info. It would be good feature to have a possibility to upload file

**Describe the solution you'd like**
It would be the other "question type" which would added to form. The binary would be stored in table with answers.

**Describe alternatives you've considered**
There is no simple alternative to this feature connected with Forms in Nextcloud

**Comment by jotoeri** [comment] 2021-02-09 11:09
Duplicate of #42
Please search for existing issues before opening new ones! 🙃

**Closed by jotoeri** 2021-02-09 11:09 UTC
Labels: 0. Needs triage, enhancement
