### ISSUE TITLE
Please make a feature for user to custom confirmation message that is shown after submitting the form

### ISSUE THREAD

**Issue by sopianamir** [nextcloud/forms#1533] opened 2023-02-22 03:17 UTC
**Nextcloud (please complete the following information):**
- Nextcloud-Version: [e.g. 19.0.0]
- Forms-Version: [e.g. 2.0.0-beta4]

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by susnux** [comment] 2023-02-23 00:53
I think you forgot to fill out the issue body.
From the title I guess this is a duplicate of https://github.com/nextcloud/forms/issues/385

**Closed by susnux** 2023-02-23 00:53 UTC
Labels: enhancement, 0. Needs triage
