### ISSUE TITLE
faster access to latest answer

### ISSUE THREAD

**Issue by Solar-Simon** [nextcloud/forms#2420] opened 2024-11-17 11:45 UTC
It would be practical for our application to have faster access to the individual results.

What counts for us is not the evaluation or any statistical values. Instead, every completed form is a request (for a Room to be rented). 

What could this look like in concrete terms?
A setting whether the form has a statistics / results preference, or the individual answers are in focus.

It would be practical if you could choose to be notified of each submitted form and have the content attached directly to the email. 
Alternatively / additionally ther could be a link straight to that result. 

It would be practical to get the single answer with one click into the clipboard.
Export and open as .md could also help. 

Thank you for this great app.

**Comment by Chartman123** [comment] 2024-11-22 08:29
Hi @Solar-Simon 

thanks for your feedback. The next time, please use our templates. They are there for a reason. Here are my responses to your requests:

> What could this look like in concrete terms? A setting whether the form has a statistics / results preference, or the individual answers are in focus.

We don't want to overload our app with settings, so this is nothing that we're currently planning to do.
 
> It would be practical if you could choose to be notified of each submitted form and have the content attached directly to the email. Alternatively / additionally ther could be a link straight to that result.

Duplicate of #1233 

> It would be practical to get the single answer with one click into the clipboard. Export and open as .md could also help.

This is not easy to do, especially now that we support file questions. You can always link the results to a spreadsheet/csv file and copy the single items from there.

So I'll close this issue for now as not planned/duplicate

**Closed by Chartman123** 2024-11-22 08:29 UTC
Labels: enhancement, 0. Needs triage
