### ISSUE TITLE
Registration counter

### ISSUE THREAD

**Issue by tjeyh** [nextcloud/forms#1429] opened 2022-12-25 16:35 UTC
**Nextcloud:**
- Nextcloud-Version: 24.0.8
- Forms-Version: 2.5.1

**Problem description**
For my small club, the Forms app is great! Among other things, we use it to create registrations for sports events. Here, the places are often limited (e.g. for the football teams).

**Solution idea**
It would therefore be great if there was an option to limit the number of registrations via the form. 
The number of places still open could still be visible for those who want to register (e.g. as a counter -> 10 places still available).
The registration could close itself after the maximum number of participants and issue a message that all places are taken.

**Alternatives**
A solution via the Polls app is conceivable. However, data such as the participant's email address cannot be requested here.

_Many thanks and I look forward to discussions._

**Comment by Chartman123** [comment] 2022-12-25 20:34
Duplicate of #596

**Closed by Chartman123** 2022-12-25 20:34 UTC
Labels: enhancement, 0. Needs triage
