### ISSUE TITLE
possibility to add picture to a question

### ISSUE THREAD

**Issue by yanetix** [nextcloud/forms#1062] opened 2021-11-01 21:43 UTC
- Nextcloud-Version: 22.2.0
- Forms-Version:  2.3.0

Currently all questions are text only. It would be very nice if you can add picture to your questions so you can ask things like, "What is the color of this cat?" "How many sides does this cube have?" etc

Its not limited to a specific type of question, could be helpful with any of the current question types.

**Comment by jotoeri** [comment] 2021-11-11 21:28
Duplicate of #1006 
Please search for existing issues before opening a new one. 😉

**Closed by jotoeri** 2021-11-11 21:28 UTC
Labels: enhancement, 0. Needs triage

**Comment by yanetix** [comment] 2021-11-11 21:45
Sorry, missed it.
