### ISSUE TITLE
Paragraph inbetween the questions.

### ISSUE THREAD

**Issue by Blackfire-dev** [nextcloud/forms#1248] opened 2022-07-10 10:56 UTC
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 24.0.2
- Forms-Version: 2.5.1

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Next to Add a question, or in add a question. A new button allowing the form owner to add more text. (not a text box or anything the user fills in) maybe a paragraph or new title etc.  

**Describe alternatives you've considered**
Thought about editing the HTML to add some `<P>` tags between some questions but I have no idea where this would go and would be a right faff.

Added a question such as multiple choice but not added any choice and used the question title, but doesn't show.

**Additional context**

**Comment by Chartman123** [comment] 2022-07-10 20:21
Duplicate of #624

**Closed by Chartman123** 2022-07-10 20:21 UTC
Labels: enhancement, 0. Needs triage
