### ISSUE TITLE
Nextcloud Forms - More customization for input validation, numeric data type, and a better datetime of form submittal 

### ISSUE THREAD

**Issue by tromlet** [nextcloud/forms#1443] opened 2023-01-03 20:34 UTC
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 23.0.3
- Forms-Version: 4.5.1

**Is your feature request related to a problem? Please describe.**

1. It would be nice to have numeric data entry, with validations for maximums and minimums and even accuracy to the decimal point (e.g. "this field cannot go below 10 or above 300", or "this field goes to the tenths place").
2. It would be nice to have some nice, pre-set data validations, such as for phone numbers, email addresses, web addresses, home addresses, etc.
3. For special uses cases, some kind of regex data validation would be nice to have.
4. The format of the date and time under the "Timestamp" column upon exporting the form responses to CSV is next to useless if that CSV needs to be imported to some other application. It would be preferable if it were a more standard, easily convertible date format.

**Describe the solution you'd like**
1. Implement a numeric data type into the Nextcloud forms app.
2. Implement data validation and customization for the numeric and "Short Text" data type in the Nextcloud forms app.
3. n/a
4. Implement two "Timestamp" columns - one human-readable, one machine-readable, so that it's easier to import and export that data. Even when I try to use the very robust `date` command on my machine, conversion from the standard output of that column (in my example, `Tuesday, January 3, 2023 at 5:32:12 PM GMT+0:00`), I get the following:

```text
$ date -d'Tuesday, January 3, 2023 at 5:32:12 PM GMT+0:00' +%Y%m%d
date: invalid date ‘Tuesday, January 3, 2023 at 5:32:12 PM GMT+0:00’
```

**Describe alternatives you've considered**
At the moment, there simply isn't a way to validate fairly simple numeric data going into, say, "Short Text" fields. We have no choice but to trust the data entry - BUT at least the form abstracts away the editing of the spreadsheet directly.

**Additional context**

**Comment by Chartman123** [comment] 2023-01-03 23:12
Duplicate of #177, #1001 

@tromlet First three items of your list can be achieved with #177. The fourth one has already been reworked in #1001

**Closed by Chartman123** 2023-01-03 23:12 UTC
Labels: enhancement, 0. Needs triage
