### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by bvn13** [nextcloud/forms#1142] opened 2022-03-25 07:29 UTC
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 23.0.3.1
- Forms-Version: 2.4.0

**Is your feature request related to a problem? Please describe.**
I struggle at placing hyperlinks into the description of the form.

**Describe the solution you'd like**
I think it will be handy to write form description in markdown mode.

**Comment by jotoeri** [comment] 2022-03-25 09:14
Duplicate of #489 
Please search for existing issues before opening a new one. 😉

**Closed by jotoeri** 2022-03-25 09:14 UTC
Labels: enhancement, 0. Needs triage
