### ISSUE TITLE
iOS / UX - Submit button hidden when App Store banner active

### ISSUE THREAD

**Issue by philffm** [nextcloud/forms#2050] opened 2024-04-06 13:11 UTC
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**

![image](https://github.com/nextcloud/forms/assets/6079545/5ed7f3ce-3fa9-4cbb-8d37-7f40f4c4182d)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Nextcloud (please complete the following information):**
- Nextcloud-Version: [e.g. 19.0.0]
- Forms-Version: [e.g. 2.0.0-beta4]

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: 17.2
 - Browser Safari

**Browser log**
```
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.
```

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Additional context**

**Comment by Chartman123** [comment] 2024-04-06 17:44
Duplicate of #1585

**Closed** 2024-04-06 17:44 UTC
Labels: bug, 0. Needs triage
