### ISSUE TITLE
Question descriptions

### ISSUE THREAD

**Issue by andreamangia** [nextcloud/forms#1027] opened 2021-08-05 05:24 UTC
**Nextcloud:**
- Nextcloud-Version: 20.0.11
- Forms-Version: 2.3.0

**Is your feature request related to a problem? Please describe.**
I am administering a Nextcloud instance that is being used inside a University research project to foster the use of digital tools that are respectful of user data and privacy. We are using NC happily in many ways. We are experiencing a small issue with the forms app: questions do not seem to have neither formatting options, nor a field to provide a description. The latter feature is commonly available in other similar tools.

**Describe the solution you'd like**
I would like to have the possibility to add a text description to each question (ideally, if the question is bold text, this should be regular).

**Describe alternatives you've considered**
As an alternative, it could be useful to have the possibility to format text (i.e. using markdown), so that the question text and the extra info would be visually different.

**Comment by jotoeri** [comment] 2021-08-05 08:01
Duplicate of #321 
Please search for existing issues before opening a new one. 😉

**Closed by jotoeri** 2021-08-05 08:01 UTC
Labels: 0. Needs triage, enhancement

**Comment by andreamangia** [comment] 2021-08-06 05:12
My bad, sorry
