### ISSUE TITLE
Feature Request: Headings, paragraph text, spacers, and pages/sections.

### ISSUE THREAD

**Issue by nooblag** [nextcloud/forms#1037] opened 2021-09-02 18:03 UTC
Great plugin!

I would love to see headings, paragraph text, and spacers be introduced to build forms with a set of questions that have explanatory text; spacers to add blank space/padding in the form; and the ability to add "page breaks" or "sections" similar to Google Forms or Easy Forms, which allows for more complex surveys and questionnaires, etc.

For example, with [the latter](https://easyforms.dev/), the UI looks like this:

![eg](https://user-images.githubusercontent.com/1122344/131893902-f5b699f7-194c-4dbe-aac5-d50b1b753c32.PNG)

They also have a [public demo](https://easyforms.dev/demo/) where you can experience the drag/drop for yourself to see what I mean more clearly.

It would be great if Nextcloud Forms could consider approaching some of these features as it develops!

**Comment by Chartman123** [comment] 2022-07-10 20:25
Isn't this at least partially a duplicate of #624?

**Comment by Chartman123** [comment] 2022-09-23 06:57
Duplicate of #624

**Closed by Chartman123** 2022-09-23 06:57 UTC
Labels: feature: ❓ question types
