### ISSUE TITLE
Sending / showing some kind of automated "success" message after user submitted a form

### ISSUE THREAD

**Issue by gpsloco** [nextcloud/forms#1871] opened 2024-01-10 13:45 UTC
**Nextcloud (please complete the following information):**
- Nextcloud-Version: [e.g. 27.1.5]
- Forms-Version: [e.g. 3.4.4]

**Is your feature request related to a problem? Please describe.**
after I publis my form and people start using it, relative many people send me a message afterwards / calling me and want to know whether their submission was successful. I take this as a proof that they do not get any kind of "thank you" after submission.

**Describe the solution you'd like**
Best would be if NC would send a automated message per email to the mail address given in the form (if there is one). 

**Describe alternatives you've considered**
I see this has spam/dsgvo implications and therefore a "thank you, your listing was successfully received" message on the screen would be such an alternative

**Comment by Chartman123** [comment] 2024-01-10 14:03
@gpsloco This is a duplicate of #525 

Every form shows a message to the user after they hit the submit button. So the second part of your issue is a feature we already have for a very long time.

**Closed by Chartman123** 2024-01-10 14:03 UTC
Labels: enhancement, 0. Needs triage
