### ISSUE TITLE
Please add Upload file option like in Google Forms

### ISSUE THREAD

**Issue by ramesh-dada** [nextcloud/forms#965] opened 2021-05-31 08:32 UTC
IT will be great and super if you will add uploading option with limited file storage as an alternative i will use nextcloud self hosted i will own my data. Just only one upload feature i am still stuck with Google forms, Hope you will add this, and Thank you so much for this plugin this is great

**Comment by jotoeri** [comment] 2021-05-31 18:09
Duplicate of #42
Please search for existing issues before opening a new one. 😉

**Closed by jotoeri** 2021-05-31 18:09 UTC
Labels: 0. Needs triage, enhancement
