### ISSUE TITLE
a11y: Editing forms without a mouse is only partially possible

### ISSUE THREAD

**Issue by fcnjd** [nextcloud/forms#1718] opened 2023-09-19 09:11 UTC
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
Dear Nextcloud team,
thank you for developing this awesome app. It's very helpful.
Since I am blind, I use a screenreader with speech, and more important, a Braille display. Therefore, I'm only relying on a keyboard and do not use a mouse. Sadly, for editting the description and the title of a form, it is necessary to click into it using the mouse, it's not enough to press the edit button. Therefore, it was not possible for me to perform this without sighted help. Also, the elements to move a question up or down are only usable with the mouse, there should be corresponding buttons (propperly labelled) to perform this.

**To Reproduce**
1. Go to 'forms'
2. Create a new form, fill it with some sample questions and view the results, possibly by sharing it
3. Press the "edit button"
4. Don't use the mouse, just try to edit title and description with the keyboard
5. Find out that it doesn't work.

**Expected behavior**
After pressing the edit button, I'd like to get the possibility to focus the input fields with the tab key and edit them. Also, I'd like to change the order of the questions.

**Nextcloud (please complete the following information):**
- Nextcloud-Version: [e.g. 19.0.0]
- Forms-Version: 3.3.1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 117.0.1

**Browser log**
```
JQMIGRATE: Migrate is installed, version 3.4.1 jquery-migrate.min.js:2:702
Proxying an event bus of version 3.0.2 with 1.3.0 index.es.js:2337:14
Proxying an event bus of version 3.0.2 with 1.3.0 index.es.js:2337:14
session heartbeat polling started session-heartbeat.js:103:9
Proxying an event bus of version 3.0.2 with 1.3.0 index.es.js:2337:14
Registering notifications container as a menu NotificationsApp.vue:219
Notifications permissions not yet requested NotificationsApp.vue:470
Polling interval updated to 30000 NotificationsApp.vue:416
Started background fetcher as session_keepalive is enabled NotificationsApp.vue:275
Got notification data, restoring default polling interval. NotificationsApp.vue:376
Got notification data, restoring default polling interval. NotificationsApp.vue:376
Got notification data, restoring default polling interval. NotificationsApp.vue:376
Got notification data, restoring default polling interval. NotificationsApp.vue:376
Got notification data, restoring default polling interval. NotificationsApp.vue:376
Got notification data, restoring default polling interval. NotificationsApp.vue:376
Got notification data, restoring default polling interval. NotificationsApp.vue:376
Got notification data, restoring default polling interval. NotificationsApp.vue:376
Got notification data, restoring default polling interval. NotificationsApp.vue:376
Got notification data, restoring default polling interval. NotificationsApp.vue:376
Got notification data, restoring default polling interval. NotificationsApp.vue:376
Slowing down notifications: Status 500 NotificationsApp.vue:391
Polling interval updated to 300000 NotificationsApp.vue:416
Started background fetcher as session_keepalive is enabled NotificationsApp.vue:275
```

**Additional context**
I use Jaws screenreader, version 2023.

**Comment by Chartman123** [comment] 2023-09-19 09:34
Hi @fcnjd 

thanks for your valuable feedback. This is already tracked, so I'll close this as duplicate of #416. Please go there and add more feedback if you think that not everything is covered there.

**Closed by Chartman123** 2023-09-19 09:34 UTC
Labels: bug, 0. Needs triage
