### ISSUE TITLE
Custom Email - confirmation for completed forms

### ISSUE THREAD

**Issue by thoralffricke** [nextcloud/forms#1719] opened 2023-09-21 07:28 UTC
**Nextcloud (please complete the following information):**
- Nextcloud-Version:27.0.2
- Forms-Version: 3.3.1
- 
**Is your feature request related to a problem? Please describe.**
Users have no idea whether the form has been submitted

**Describe the solution you'd like**
We would like to have the option to define a field that gives the user feedback that we can edit when the completed form has been submitted.
So a confirmation email is generated to the user.
For example, an additional field could be selectable in the selection menu when creating forms that is called e-mail address and the confirmation email will then be sent to this.
The text of the confirmation email should be presettable/editable and include the option of automatically taking over content from the form (e.g. name as salutation)

**Describe alternatives you've considered**

**Additional context**
We use the form to register for events and are constantly asked whether the registration has arrived. We would like to minimize that in this way

**Comment by Chartman123** [comment] 2023-09-21 07:40
Duplicate of #525

**Closed by Chartman123** 2023-09-21 07:40 UTC
Labels: enhancement, 0. Needs triage
