### ISSUE TITLE
Markdown: Missing top margin on block elements

### ISSUE THREAD

**Issue by gohrner** [nextcloud/forms#1566] opened 2023-03-16 21:24 UTC
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
It is not possible to have an emtpy row before a Markdown code block.

**To Reproduce**
1. Enter description field in edit mode.
2. Enter text followed by a few empty lines, followed by three-backtick-codeblock.
3. Leave edit mode.
4. No space will be between the text and the code block.

**Expected behavior**
At least one empty line should stay between the text and the code block.

**Screenshots**
![Peek 2023-03-16 22-23](https://user-images.githubusercontent.com/26199042/225755868-239561b3-e78d-4ed2-a495-5b9eda9f3bbe.gif)

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 25.0.4
- Forms-Version: 3.2.0

**Desktop (please complete the following information):**
 - OS: KDE neon (Ubuntu 22.04)
 - Browser: Chromium
 - Version 111.0.5563.64 (Offizieller Build) Built on Ubuntu , running on neon 22.04 (64-Bit)

**Comment by susnux** [comment] 2023-03-17 13:55
> It is not possible to have an emtpy row before a Markdown code block.

That is not supported by Markdown, markdown treats multiple empty lines as one single line.
Meaning regardless of the number of empty lines, they will only result in a new paragraph.

So this is not a bug but by definition.

FYI: It is possible to have empty lines within one block:
```markdown
some text\
\
\
\
3 empty lines before this
```

Looks like this:
some text\
\
\
\
3 empty lines before this

**Comment by susnux** [comment] 2023-03-17 16:23
This is a styling issue, I will submit a fix for this asap.

**Closed** 2023-03-18 22:51 UTC
Labels: bug, design, 3. to review
