### ISSUE TITLE
API event on submission 

### ISSUE THREAD

**Issue by pascalfranke** [nextcloud/forms#1686] opened 2023-08-08 19:56 UTC
I was wondering if there could be an endpoint for form submission. If a form was sent an event will be triggered that can be received via Websockets.

This feature could be useful in situations where you want to automatically process sent forms or to notify users.

Please let me know if something similar to this already exists

**Comment by Chartman123** [comment] 2023-08-09 06:00
Duplicate of #1223

**Closed** 2023-08-09 06:00 UTC
Labels: duplicate
