### ISSUE TITLE
How to edit a form later?

### ISSUE THREAD

**Issue by jgrete** [nextcloud/forms#7] opened 2019-05-31 08:32 UTC
**Which Forms version are you running? 0.2

**Nextcloud or ownCloud?:nextcloud

**Nextcloud/ownCloud version:16.0.x

### Steps to reproduce
1. create and finish a form
2. try to edit this form later
3.

### Actual behaviour
No edit button or something like that

### Expected behaviour
Editing should be possible, maybe only as long as no answers were made

**Comment by luixxiul** [comment] 2019-05-31 08:48
Looks like this is a duplicate of https://github.com/affan98/forms/issues/1.

**Comment by jancborchardt** [comment] 2019-06-11 13:42
Yep, this can be closed as duplicate. :)

**Comment by luixxiul** [comment] 2020-01-15 16:20
Closing as duplicate.

**Closed by luixxiul** 2020-01-15 16:20 UTC
Labels: duplicate
