### ISSUE TITLE
Cannot find "Multiple choice" English wording and its French translation "Choix multiples" in Transiflex

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/forms#1341] opened 2022-09-15 08:35 UTC
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
**My first request :** 
I would have appreciated renaming the "Multiple choice" English wording because it's confusing for users. 
I think checkboxes are multiple choice answers but radio buttons are unique choice answers.
**My second request (the most important for me and other French users) :**
I would like to replace the French translation with another (more understandable) which isn't a literal translation BTW.
The problem is that I cannot find at all the "Multiple choice" english wording and its French translation in Transiflex.
I've also looked at the /[l10n]/fr.js file and the following line doesn't exist in it : 
`"Multiple choice" : "Choix multiples",`
Can you have a look at it ?

![2022-09-15_10-21](https://user-images.githubusercontent.com/33763786/190355063-b224425e-1b72-4aaf-a94e-3be542de0951.png)

**Comment by Chartman123** [comment] 2022-09-15 08:49
Duplicate of #1190

**Closed by Chartman123** 2022-09-15 08:49 UTC
Labels: bug, 0. Needs triage
