### ISSUE TITLE
share form with users group?

### ISSUE THREAD

**Issue by 2epal** [nextcloud/forms#576] opened 2020-08-26 10:02 UTC
**Describe the bug**
 i thought that the form will displayed automatically at the targeted users ...but no

**To Reproduce**
1.nextcloud 19 fresh installation linux shared hosting
2.add forms app
3.create a new form
4.to share: select a group of users, or all,     (no link option)
but nothning happens. i thought that the form will displayed automatically at the targeted users ...but no

**Expected behavior**
 i thought that the form will displayed automatically at the targeted users ...but no

**Screenshots**

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 19
- Forms-Version: 2.03

**Desktop (please complete the following information):**
 - OS: win7
 - Browser firefox 
 - Version 79 32bit

**Comment by skjnldsv** [comment] 2020-08-26 10:06
Duplicate of #322 and/or #364

**Closed by skjnldsv** 2020-08-26 10:06 UTC
Labels: 0. Needs triage, bug
