### ISSUE TITLE
Integration to Activity App

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud/forms#318] opened 2020-04-30 13:58 UTC
Hi!

As I wrote it in #316, It would be really nice to see an integration to the Activity App, like Files, Talk and Deck has.

Just a few points for what it would be nice to get an info in your stream or per E-Mail:
- Notification if an anonyme user has sent an answer to a form (if unregistred user or "anonym answer" is checked on a Form)
- Notification if an registred user has sent an answer to a form
- maybe more?

If I talk about notifications, it also would be nice to decide for every single board to enable notifications or not.

If you need any more infos/examples, just ask.

**Comment by jancborchardt** [comment] 2020-05-01 00:20
This is actually a duplicate of https://github.com/nextcloud/forms/issues/12 – moved your comment there, let’s continue over there. :) (Sorry, I should have spotted the duplicate already in the other overview issue.)

**Closed by jancborchardt** 2020-05-01 00:20 UTC
Labels: 1. to develop, enhancement, feature: responses & statistics, integration
