### ISSUE TITLE
Condition-based questions

### ISSUE THREAD

**Issue by tomraedle** [nextcloud/forms#876] opened 2021-04-01 08:20 UTC
To get on a next level, forms should handle condition-based questions like:
"If question "A" was answered with "O" then next Question is "M" else if question "A" was answered with "P" then next Question is "N" and so on.

**Comment by jotoeri** [comment] 2021-04-04 21:58
Duplicate of #358
Please search for existing issues, before opening a new one. 😉

**Closed by jotoeri** 2021-04-04 21:58 UTC
