### ISSUE TITLE
Add Picture to answer 

### ISSUE THREAD

**Issue by svenweida** [nextcloud/forms#2169] opened 2024-05-15 16:01 UTC
**Nextcloud (please complete the following information):**
- Nextcloud-Version: [e.g. 19.0.0]
- Forms-Version: [e.g. 2.0.0-beta4]
Use form as well with pictures could open a range of by your teeth to use the application.

**Describe the solution you'd like**
A kind of answer would be to make upload or choose a picture from the current device

**Additional context**
Using forms as well with the possibility to upload pictures would open a range of use cases. Like to ask for a picture if it’s a kind of ticket system

**Comment by Chartman123** [comment] 2024-05-15 22:03
Duplicate of #42

**Closed** 2024-05-15 22:03 UTC
Labels: duplicate
