### ISSUE TITLE
[feature request] Add read-only NOTE text into the forms

### ISSUE THREAD

**Issue by TCI2020** [nextcloud/forms#1187] opened 2022-04-25 16:05 UTC
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 22.2.6
- Forms-Version: 2.5.0

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
When a form is designed, I noticed that sometimes I would like to add a multi-line note between the questions. For example: a description/summary, for the following group of questions.

**Describe alternatives you've considered**
So far, I am using a non-mandatory text field where the answer field can be blank.

**Additional context**
It would be very helpful if such a field (Read-only NOTE) can be added into the forms as a formatted text with the following basic options: Multi-line, Bold symbols, Italic symbols, Underline symbols
The formatted text will allow the users to create a nice description section inside the forms.

**Comment by Chartman123** [comment] 2022-04-25 18:39
Duplicate of #624

**Closed by Chartman123** 2022-04-25 18:39 UTC
Labels: enhancement, 0. Needs triage
