### ISSUE TITLE
Two dimensional array

### ISSUE THREAD

**Issue by sachaz** [nextcloud/forms#1584] opened 2023-04-02 09:08 UTC
Please add the feature for a two dimensional array.

Like in other tools to do forms, it cool be very cool to have an array like this following example :

| Questions | Day 1 | Day 2 |
|--- | ----- | ----- |
|question 1 | X | |
|question 2 | | X |

**Comment by Chartman123** [comment] 2023-04-02 19:45
Duplicate of #356

**Closed by Chartman123** 2023-04-02 19:45 UTC
Labels: enhancement, 0. Needs triage
