### ISSUE TITLE
Add images with description

### ISSUE THREAD

**Issue by Andreas-Kainz** [nextcloud/forms#1229] opened 2022-06-21 08:20 UTC
I would like to use forms to make inspections.

The workflow is that I go to make an inspection and add to some questions pictures, done by the mobile. So the images were part of the form.

**Comment by jotoeri** [comment] 2022-06-30 06:09
Duplicate of #1006 
Please search for existing issues before opening a new one. 😉

**Closed by jotoeri** 2022-06-30 06:09 UTC
Labels: enhancement, 0. Needs triage
