### ISSUE TITLE
Custom note after submitting

### ISSUE THREAD

**Issue by aparcar** [nextcloud/forms#1250] opened 2022-07-10 14:23 UTC
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 24
- Forms-Version: 2.5.1

**Is your feature request related to a problem? Please describe.**

I'd like to collect forms and email addresses separately, so no email can be linked to answers. My idea was to have to forms and after finishing the actual survey, a note is shown to add an email address (in a second form).

However the notification after submitting is static and it's not possible to add a custom note.

**Describe the solution you'd like**

Ideally the submit note would be as easy editable as the introduction text.

**Describe alternatives you've considered**

Setting up LimeSurvey but that doesn't seem like a nice solution.

**Comment by jotoeri** [comment] 2022-07-10 15:17
Duplicate of #385 
Please search for existing issues before opening a new one. 😉

**Closed by jotoeri** 2022-07-10 15:17 UTC
Labels: enhancement, 0. Needs triage
