### ISSUE TITLE
Add pages to forms

### ISSUE THREAD

**Issue by orionpy** [nextcloud/forms#1987] opened 2024-02-27 14:22 UTC
**Nextcloud (please complete the following information):**
- Nextcloud-Version: [e.g. 28.0.2]
- Forms-Version: [e.g. 2.0.0-beta4]

In some cases, it is necessary to build forms that require multiple sheets. Example:
Page 1: General Conditions Message. And a conditional . If no, Cancel Form.
Page 2: Various Questions.
Page 3: Satisfaction of the form.

**Comment by Chartman123** [comment] 2024-02-27 14:52
Duplicate of #357

**Closed by Chartman123** 2024-02-27 14:52 UTC
Labels: enhancement, 0. Needs triage
