### ISSUE TITLE
Signature field on forms app

### ISSUE THREAD

**Issue by geckigek** [nextcloud/forms#1757] opened 2023-10-22 07:56 UTC
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 26.0.4 and on going
- Forms-Version: 3.3.1

**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

I would like to have a signature field on the forms App. The background on this feature request is that we would like to use the forms app to fill in a registration form for children for a weekend trip. The parents have to agree to the terms of registration with a signature.

First/preferred idea would to do the signature with an touch Pad/pencil. 

Second idea would to auto generate a signature based on the logged in user.

**Comment by Chartman123** [comment] 2023-10-22 09:45
Duplicate of #947

**Closed** 2023-10-22 09:45 UTC
Labels: enhancement, 0. Needs triage
