### ISSUE TITLE
Allow change the order of answer options.

### ISSUE THREAD

**Issue by TUCAOEVER** [nextcloud/forms#2316] opened 2024-09-11 01:49 UTC
**Nextcloud (please complete the following information):**

-   Nextcloud-Version: 29.0.6
-   Forms-Version: 4.3.0-alpha7 (Unstable)

**Is your feature request related to a problem? Please describe.**
Sometimes i missed adding some answer option which needs to be in the middle of the options, i need to reorganize all options in order to reach this point. 

**Describe the solution you'd like**
The questions list could be simply resorted, it should be same with the answer options.

**Describe alternatives you've considered**
None for now.

**Additional context**
![QQ_1726019364864](https://github.com/user-attachments/assets/56c6b277-cffe-48f9-a934-3bfdee672e8a)
Just like this.

**Comment by Chartman123** [comment] 2024-09-11 06:20
Please use the search function before opening new issues... Duplicate of #354

**Closed by Chartman123** 2024-09-11 06:20 UTC
Labels: enhancement, 0. Needs triage
