### ISSUE TITLE
dependent questions

### ISSUE THREAD

**Issue by lfreist** [nextcloud/forms#948] opened 2021-05-21 08:49 UTC
**Nextcloud:**
- Nextcloud-Version: [e.g. 20.0.0]

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A depending question tool. Questions only shown, if another question got a specific answer

**Comment by jotoeri** [comment] 2021-05-21 10:39
Duplicate of #358 
Please search for existing issues before opening a new one. 😉

**Closed by jotoeri** 2021-05-21 10:39 UTC
Labels: 0. Needs triage, enhancement
