### ISSUE TITLE
Allow attach file to form

### ISSUE THREAD

**Issue by supernovae** [nextcloud/forms#2338] opened 2024-09-27 22:05 UTC
**Nextcloud (please complete the following information):**

-   Nextcloud-Version: [29.0.5]
-   Forms-Version: [4.2.4]

**Is your feature request related to a problem? Please describe.**
I would like the ability to allow someone to attach a file - in this specific case, a screenshot or image - but any file type that could be saved would be nice.

**Describe the solution you'd like**
Add a new form field for file upload/attachment.

**Describe alternatives you've considered**
Right now I have people upload in their repo and then copy and paste a link as text file, it's not very pretty. I would like files to remain with form rather than potentially disappear as users manage their own storage.

**Additional context**
Allow attaching of a file to a form submission. Perhaps configurable as to file extension or types supported and max size for form.

**Comment by Chartman123** [comment] 2024-09-27 22:10
Duplicate of #42

**Closed by Chartman123** 2024-09-27 22:10 UTC
Labels: enhancement, 0. Needs triage

**Comment by supercon99** [comment] 2025-04-06 14:24
This was linked to forms #42, but is also set to closed label.
