### ISSUE TITLE
Manualy close form

### ISSUE THREAD

**Issue by SebastianV-2021** [nextcloud/forms#1773] opened 2023-11-07 20:16 UTC
As an admin I would like to manually close a form.
Currently the form closes automatically when an expiratiion date is set and reached. Unfortunately it's not possible to close it manually.

"Reopen" would be great too. Just like I change the expiration date to sometime in the future.

**Comment by Chartman123** [comment] 2023-11-07 21:18
Duplicate of #1101

**Closed** 2023-11-07 21:18 UTC
Labels: enhancement, 0. Needs triage
