### ISSUE TITLE
copy question(s)

### ISSUE THREAD

**Issue by gitHost7** [nextcloud/forms#1002] opened 2021-07-02 12:22 UTC
**Nextcloud (please complete the following information):**
- Nextcloud-Version: [21.0.3]
- Forms-Version: [2.2.4]

**Is your feature request related to a problem? Please describe.**
When creating forms i often have similar questions (or better the same answers to a question). If there are many answers to a question then it's frustrating that every answer to a new questions again needs to be entered manually.
![image](https://user-images.githubusercontent.com/86683636/124273311-216b4480-db40-11eb-9c02-cd2e53d313d8.png)

**Describe the solution you'd like**
Would be great to get an additional option under the three dots beside the question and find "copy question" there

**Describe alternatives you've considered**
enter every question and answer manually by hand :-/

**Comment by jotoeri** [comment] 2021-07-02 14:09
Duplicate of #595 
Please search for existing issues before opening a new one. 😉

**Closed by jotoeri** 2021-07-02 14:09 UTC
Labels: 0. Needs triage, enhancement

**Comment by gitHost7** [comment] 2021-07-02 16:27
Thank you!
Was only searching for "copy" (not for "duplicate") and wondered that this feature was not already req'ed. But it was as you mentioned :)
