### ISSUE TITLE
Forms 4.0.0 emtpy page after nextcloud 28.0.1. upgrade

### ISSUE THREAD

**Issue by nicovd737** [nextcloud/forms#1883] opened 2024-01-18 12:33 UTC
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
Since nextcloud 28.0.1 upgrade, form app is not working anymore. When we clik on form, it just lead to empty page. 
No more forms are accessible for anybody.

**To Reproduce**
1. Go to 'Forms'
2. See blank page

**Expected behavior**
See all forms for each users.

**Screenshots**
![image](https://github.com/nextcloud/forms/assets/28760546/52bbb81c-b7a2-446a-b774-8520d731d4e4)

**Nextcloud (please complete the following information):**
- Nextcloud-Version: [28.0.1.]
- Forms-Version: [4.0.0]

**Desktop (please complete the following information):**
 - OS: [all]
 - Browser [all]

**Smartphone (please complete the following information):**
 - Device: [all]
 - OS: [all]
 - Browser [all]

Logs:

{"reqId":"QaSkDLYiNzgWVGGHVoBX","level":0,"time":"2024-01-18T14:32:00+02:00","remoteAddr":"10.203.2.158","user":"xxx","app":"PHP","method":"GET","url":"/apps/side_menu/css/stylesheet?v=7","message":"Implicit conversion from float 175.95 to int loses precision at /var/www/html/custom_apps/side_menu/lib/Controller/CssController.php#155","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0","version":"28.0.1.1","data":{"app":"PHP"}}

<details>

**Comment by Chartman123** [comment] 2024-01-18 12:39
Duplicate of #1838

**Closed by Chartman123** 2024-01-18 12:39 UTC
Labels: bug, 0. Needs triage
