### ISSUE TITLE
Numeric Answer

### ISSUE THREAD

**Issue by lfreist** [nextcloud/forms#949] opened 2021-05-21 08:52 UTC
**Nextcloud:**
- Nextcloud-Version: 20.0.8

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Numeric answer fields. Questions that can only be answered with a numeric type (Selection (Integer or Float)?)

**Comment by jotoeri** [comment] 2021-05-21 10:37
Duplicate of #177 
Please search for existing issues before opening a new one. 😉

**Closed by jotoeri** 2021-05-21 10:37 UTC
Labels: 0. Needs triage, enhancement
