### ISSUE TITLE
Reorder answers for multi answer question (checkbox, radio or dropdown)

### ISSUE THREAD

**Issue by sbernard31** [nextcloud/forms#935] opened 2021-05-12 13:48 UTC
- Nextcloud-Version: 19.0.4
- Forms-Version: 2.2.2

For multi answer question (dropdown, radio, checkbox), If you create a long list of answer and want to insert a new one at a specific index you need to delete all until the desired index, add your new answer and recreate all the ones you just deleted. 

It could be great to be able to reorder answer. 

An alternative could be to be able to add answer directly at a specific index.

**Comment by sbernard31** [comment] 2021-05-12 14:02
Most of the time when answer order matters this is because answers are listed in alphabetical order and so insert a new answer at right place could be painful. 

Another alternative (maybe even a new feature, I can create a new ticket if needed) could be to let the application sort answer by alphabetic order. So for multi answer question you could choose : 
 - insertion order or alphabetic order
 - descending or ascending order
 
 Another alternative could be to add an key index field for each option which will be used for sorting the answers.

**Comment by jotoeri** [comment] 2021-05-19 20:44
Duplicate of #354
Please search for existing issues before opening a new one. 😉

**Closed by jotoeri** 2021-05-19 20:44 UTC
Labels: 0. Needs triage, enhancement
